
'use server';

/**
 * @fileOverview An AI agent that generates a Facebook cover photo based on business details.
 */
import { ai } from '@/ai/genkit';
import { z } from 'zod';
import { generateImage } from './image-generator';
import { transformImage } from './image-transformer';

export const FacebookCoverInputSchema = z.object({
  businessName: z.string().min(1, "Business name is required."),
  tagline: z.string().optional(),
  businessDescription: z.string().min(10, "Please provide a brief description of your business."),
  styleAndImagery: z.string().min(10, "Please describe the desired style and imagery."),
});
export type FacebookCoverInput = z.infer<typeof FacebookCoverInputSchema>;

export const FacebookCoverOutputSchema = z.object({
  coverPhotoUrl: z.string().url().describe("A data URI of the final, generated Facebook cover photo."),
  baseImageUrl: z.string().url().describe("A data URI of the base background image generated by the AI."),
});
export type FacebookCoverOutput = z.infer<typeof FacebookCoverOutputSchema>;

export const generateFacebookCover = ai.defineFlow(
  {
    name: 'generateFacebookCover',
    inputSchema: FacebookCoverInputSchema,
    outputSchema: FacebookCoverOutputSchema,
  },
  async (input) => {
    // Step 1: Generate a high-quality base background image.
    const imageResult = await generateImage({
      prompt: `Generate a high-quality, visually appealing background image suitable for a Facebook cover. The theme should be related to "${input.businessDescription}" with a style of "${input.styleAndImagery}". The image should be scenic and professional, with plenty of clean space on the left side for text. No text should be on the image. Dimensions 851x315 pixels.`,
    });
    
    if (!imageResult.imageUrl) {
        throw new Error("Base image generation failed.");
    }

    // Step 2: Use the image-to-image model to overlay text professionally.
    const textOverlayPrompt = `
      Overlay the following text onto the left side of the provided image to create a professional Facebook cover photo.
      
      - Business Name (Large, bold font): "${input.businessName}"
      - Tagline (Smaller font, below the name): "${input.tagline || ''}"

      The text should be white with a subtle drop shadow for readability. Ensure the text is well-placed, aesthetically pleasing, and does not obscure key parts of the background image. The final image size must be 851x315 pixels.
    `;
    
    const finalImageResult = await transformImage({
        baseImageUri: imageResult.imageUrl,
        prompt: textOverlayPrompt,
    });

    if (!finalImageResult.imageDataUri) {
      throw new Error('Text overlay transformation failed.');
    }

    return {
      coverPhotoUrl: finalImageResult.imageDataUri,
      baseImageUrl: imageResult.imageUrl,
    };
  }
);
