
export interface InvestorDocument {
    name: string;
    dataUri: string;
}

export interface Investor {
  id: string;
  name: string;
  type: 'Investor' | 'Funder';
  subType: 'Personal/Private' | 'Angel' | 'Institute/Government' | 'VC Fund';
  profile: string;
  focusArea: string;
  country: string;
  documents: {
    cr?: InvestorDocument;
    vatId?: InvestorDocument;
    passport?: InvestorDocument;
    civilId?: InvestorDocument;
    incomeProof?: InvestorDocument;
  };
  investmentValue?: number;
  sharePercentage?: number;
}

export const initialInvestors: Investor[] = [
    {
        id: "inv_1",
        name: "Oman Technology Fund",
        type: "Funder",
        subType: "Institute/Government",
        profile: "A government-backed fund focused on nurturing technology startups and innovation within the Sultanate of Oman.",
        focusArea: "Technology Startups",
        country: "Oman",
        documents: {},
        investmentValue: 50000,
        sharePercentage: 0,
    },
    {
        id: "inv_2",
        name: "Future Growth Ventures",
        type: "Investor",
        subType: "VC Fund",
        profile: "A Dubai-based Venture Capital fund investing in early-stage SaaS and AI companies across the GCC.",
        focusArea: "SaaS & AI",
        country: "UAE",
        documents: {},
        investmentValue: 150000,
        sharePercentage: 15,
    },
    {
        id: "inv_3",
        name: "Ali Al-Saidi",
        type: "Investor",
        subType: "Angel",
        profile: "An individual angel investor with a background in logistics and supply chain technology. Focused on the 'Logistics Chain AI' project.",
        focusArea: "Logistics & Supply Chain Tech",
        country: "Oman",
        documents: {},
        investmentValue: 25000,
        sharePercentage: 5,
    },
     {
        id: "inv_4",
        name: "SME Development Fund (Inma)",
        type: "Funder",
        subType: "Institute/Government",
        profile: "Provides financial solutions and support for the growth and development of Small and Medium Enterprises in Oman.",
        focusArea: "General SME Growth",
        country: "Oman",
        documents: {},
        investmentValue: 75000,
        sharePercentage: 0,
    },
    {
        id: "inv_5",
        name: "TechStars Middle East",
        type: "Investor",
        subType: "VC Fund",
        profile: "Global accelerator and seed-stage investor focusing on tech startups. Interested in our AI agent ecosystem.",
        focusArea: "AI Ecosystems",
        country: "UAE",
        documents: {},
        investmentValue: 120000,
        sharePercentage: 7,
    },
    {
        id: "inv_6",
        name: "Fatima Al-Marzooqi",
        type: "Investor",
        subType: "Angel",
        profile: "Experienced fintech professional investing in digital payment and identity solutions. Specific interest in the 'Ameen' project.",
        focusArea: "Fintech & Digital Identity",
        country: "Bahrain",
        documents: {},
        investmentValue: 50000,
        sharePercentage: 4,
    },
    {
        id: "inv_7",
        name: "Innovate Ventures",
        type: "Investor",
        subType: "VC Fund",
        profile: "Venture fund specializing in B2B SaaS platforms. Looking at our overall business platform for a potential series A.",
        focusArea: "B2B SaaS Platforms",
        country: "USA",
        documents: {},
        investmentValue: 500000,
        sharePercentage: 20,
    },
    {
        id: "inv_8",
        name: "KSA Vision Fund",
        type: "Funder",
        subType: "Institute/Government",
        profile: "Saudi Arabian sovereign wealth fund with a mandate to invest in regional high-growth technology companies.",
        focusArea: "Regional Tech Growth",
        country: "Saudi Arabia",
        documents: {},
        investmentValue: 1000000,
        sharePercentage: 18,
    },
    {
        id: "inv_9",
        name: "Mohammed bin Rashid Innovation Fund",
        type: "Funder",
        subType: "Institute/Government",
        profile: "A federal initiative in the UAE to support innovators in key sectors.",
        focusArea: "Key Sector Innovation (UAE)",
        country: "UAE",
        documents: {},
        investmentValue: 100000,
        sharePercentage: 0,
    },
    {
        id: "inv_10",
        name: "Ahmed Al Balushi",
        type: "Investor",
        subType: "Personal/Private",
        profile: "Local businessman investing in promising Omani SMEs for portfolio diversification. General company investment.",
        focusArea: "General Corporate",
        country: "Oman",
        documents: {},
        investmentValue: 30000,
        sharePercentage: 2,
    },
    {
        id: "inv_11",
        name: "Global AI Angels",
        type: "Investor",
        subType: "Angel",
        profile: "A syndicate of angel investors focused exclusively on artificial intelligence startups.",
        focusArea: "Artificial Intelligence",
        country: "USA",
        documents: {},
        investmentValue: 75000,
        sharePercentage: 6,
    },
    {
        id: "inv_12",
        name: "Real Estate Tech Partners",
        type: "Investor",
        subType: "VC Fund",
        profile: "A fund dedicated to prop-tech. Interested in the 'AI Property Valuator' and 'SmartLease Manager' projects.",
        focusArea: "Real Estate Tech",
        country: "UK",
        documents: {},
        investmentValue: 200000,
        sharePercentage: 10,
    },
    {
        id: "inv_13",
        name: "Construction Innovation Fund",
        type: "Investor",
        subType: "VC Fund",
        profile: "A corporate venture fund from a major construction company looking to invest in construction technology. Specific interest in our 'Smart PM SaaS'.",
        focusArea: "Construction Tech",
        country: "Germany",
        documents: {},
        investmentValue: 250000,
        sharePercentage: 12,
    },
    {
        id: "inv_14",
        name: "Oman Chamber of Commerce & Industry (OCCI)",
        type: "Funder",
        subType: "Institute/Government",
        profile: "Offering a grant to promote digital solutions for local businesses.",
        focusArea: "Local Business Digitization",
        country: "Oman",
        documents: {},
        investmentValue: 20000,
        sharePercentage: 0,
    },
    {
        id: "inv_15",
        name: "Noora Al-Harthi",
        type: "Investor",
        subType: "Personal/Private",
        profile: "Private investor looking for opportunities in e-commerce and digital marketplaces. Interested in 'Nova Commerce'.",
        focusArea: "E-commerce",
        country: "Oman",
        documents: {},
        investmentValue: 40000,
        sharePercentage: 3,
    },
    {
        id: "inv_16",
        name: "MENA Growth Fund",
        type: "Investor",
        subType: "VC Fund",
        profile: "A large fund focusing on scale-up companies in the Middle East and North Africa.",
        focusArea: "MENA Scale-ups",
        country: "Bahrain",
        documents: {},
        investmentValue: 750000,
        sharePercentage: 15,
    },
    {
        id: "inv_17",
        name: "Cybersecurity Ventures",
        type: "Investor",
        subType: "VC Fund",
        profile: "Specialist fund for cybersecurity startups. Looking at our 'Aegis Security' service line.",
        focusArea: "Cybersecurity",
        country: "USA",
        documents: {},
        investmentValue: 100000,
        sharePercentage: 8,
    },
    {
        id: "inv_18",
        name: "The Impact Fund",
        type: "Funder",
        subType: "Angel",
        profile: "A philanthropic fund supporting businesses that create a positive social or environmental impact.",
        focusArea: "Social & Environmental Impact",
        country: "Switzerland",
        documents: {},
        investmentValue: 50000,
        sharePercentage: 0,
    },
    {
        id: "inv_19",
        name: "Yousef Al-Khanji",
        type: "Investor",
        subType: "Angel",
        profile: "Serial entrepreneur and angel investor from Qatar, looking for his next big bet in AI.",
        focusArea: "AI Ventures (Qatar)",
        country: "Qatar",
        documents: {},
        investmentValue: 100000,
        sharePercentage: 5,
    },
    {
        id: "inv_20",
        name: "Family Office of Al-Futtaim",
        type: "Investor",
        subType: "Personal/Private",
        profile: "A private family office looking for long-term, stable investments in regional technology leaders.",
        focusArea: "Long-term Regional Tech",
        country: "UAE",
        documents: {},
        investmentValue: 300000,
        sharePercentage: 10,
    },
    {
        id: "inv_21",
        name: "Bahrain Development Bank",
        type: "Funder",
        subType: "Institute/Government",
        profile: "Offering development loans and funding for businesses expanding into Bahrain.",
        focusArea: "Bahrain Expansion",
        country: "Bahrain",
        documents: {},
        investmentValue: 150000,
        sharePercentage: 0,
    },
    {
        id: "inv_22",
        name: "Digital Transformation Grant",
        type: "Funder",
        subType: "Institute/Government",
        profile: "A grant offered by the Ministry of Transport, Communications and IT for projects that digitize traditional industries.",
        focusArea: "Industry Digitization",
        country: "Oman",
        documents: {},
        investmentValue: 40000,
        sharePercentage: 0,
    },
    {
        id: "inv_23",
        name: "Sultan Qaboos University Tech Fund",
        type: "Investor",
        subType: "Institute/Government",
        profile: "University-affiliated fund that invests in spin-off technologies and student-led startups.",
        focusArea: "University Spin-offs",
        country: "Oman",
        documents: {},
        investmentValue: 15000,
        sharePercentage: 2,
    },
    {
        id: "inv_24",
        name: "Salim Al-Ghanim",
        type: "Investor",
        subType: "Personal/Private",
        profile: "Retired oil and gas executive, now a private investor focusing on renewable energy and sustainability tech.",
        focusArea: "Renewable Energy Tech",
        country: "Kuwait",
        documents: {},
        investmentValue: 200000,
        sharePercentage: 8,
    }
];
