
export interface Product {
    id: number;
    name: string;
    description: string;
    stage: string;
    category: string;
    price: number;
    image: string;
    aiHint: string;
    rating: number;
    enabled: boolean;
    href?: string;
}

export const initialProducts: Product[] = [
    {
        id: 1,
        name: "Wireless Headphones",
        description: "High-fidelity audio with noise cancellation.",
        stage: "Live & Operating",
        category: "Electronics",
        price: 1.3,
        image: "https://picsum.photos/seed/p1/400/400",
        aiHint: "headphones product",
        rating: 4.5,
        enabled: true,
    },
    {
        id: 2,
        name: "Modern Coffee Table",
        description: "Oak wood with a minimalist design for modern living.",
        stage: "Live & Operating",
        category: "Home Goods",
        price: 2.5,
        image: "https://picsum.photos/seed/p2/400/400",
        aiHint: "coffee table",
        rating: 4.8,
        enabled: true,
    },
    {
        id: 3,
        name: "Performance Running Shoes",
        description: "Lightweight and responsive for your daily run.",
        stage: "Live & Operating",
        category: "Sports",
        price: 0.9,
        image: "https://picsum.photos/seed/p3/400/400",
        aiHint: "running shoes",
        rating: 4.7,
        enabled: true,
    },
    {
        id: 4,
        name: "Organic Cotton T-Shirt",
        description: "Soft, breathable, and sustainably made.",
        stage: "Live & Operating",
        category: "Apparel",
        price: 0.25,
        image: "https://picsum.photos/seed/p4/400/400",
        aiHint: "cotton t-shirt",
        rating: 4.9,
        enabled: true,
    },
     {
        id: 5,
        name: "Smartwatch Series 8",
        description: "Track your fitness and stay connected on the go.",
        stage: "Live & Operating",
        category: "Electronics",
        price: 4.0,
        image: "https://picsum.photos/seed/p5/400/400",
        aiHint: "smartwatch product",
        rating: 4.9,
        enabled: true,
    },
    {
        id: 6,
        name: "Leather Backpack",
        description: "Stylish and durable for work or travel.",
        stage: "Live & Operating",
        category: "Apparel",
        price: 1.5,
        image: "https://picsum.photos/seed/p6/400/400",
        aiHint: "leather backpack",
        rating: 4.6,
        enabled: true,
    },
    {
        id: 7,
        name: "Non-stick Cookware Set",
        description: "A complete set for all your cooking needs.",
        stage: "Live & Operating",
        category: "Home Goods",
        price: 2.0,
        image: "https://picsum.photos/seed/p7/400/400",
        aiHint: "cookware set",
        rating: 4.7,
        enabled: true,
    },
    {
        id: 8,
        name: "The Alchemist",
        description: "A bestselling novel by Paulo Coelho.",
        stage: "Live & Operating",
        category: "Books",
        price: 0.13,
        image: "https://picsum.photos/seed/p8/400/400",
        aiHint: "book cover",
        rating: 4.8,
        enabled: true,
    },
    {
        id: 9,
        name: "Smart PM SaaS",
        description: "AI-based scheduling, Gantt charts, resource allocation, real-time collaboration, and document management.",
        stage: "Idea Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const1/400/400",
        aiHint: "construction management software",
        rating: 0,
        enabled: true,
        href: "/construction-tech/smart-pm",
    },
    {
        id: 10,
        name: "BidWise Estimator",
        description: "Automated cost estimation (material, labor, equipment) and tender management platform with dynamic pricing.",
        stage: "Development Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const2/400/400",
        aiHint: "construction bidding document",
        rating: 0,
        enabled: true,
        href: "/construction-tech/bid-estimator",
    },
    {
        id: 11,
        name: "StructurAI BIM",
        description: "AI-powered BIM for automated clash detection, material optimization, and AutoCAD-to-BIM conversions.",
        stage: "Idea Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const3/400/400",
        aiHint: "building information modeling",
        rating: 0,
        enabled: true,
        href: "/construction-tech/bim",
    },
    {
        id: 12,
        name: "SiteGuard Compliance",
        description: "Mobile safety inspection app with AI image recognition for PPE violations and automated permit tracking.",
        stage: "Planning Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const4/400/400",
        aiHint: "construction safety compliance",
        rating: 0,
        enabled: true,
        href: "/construction-tech/site-guard",
    },
    {
        id: 13,
        name: "WorkforceFlow",
        description: "AI-driven workforce scheduling, digital timecards with face recognition, and IoT equipment tracking.",
        stage: "Idea Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const5/400/400",
        aiHint: "construction workforce management",
        rating: 0,
        enabled: true,
        href: "/construction-tech/workforce-flow",
    },
    {
        id: 14,
        name: "ProcureChain SaaS",
        description: "E-procurement platform with automated vendor approvals, predictive ordering, and blockchain smart contracts.",
        stage: "Research Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const6/400/400",
        aiHint: "supply chain logistics",
        rating: 0,
        enabled: true,
        href: "/construction-tech/procure-chain",
    },
    {
        id: 15,
        name: "ConstructFin",
        description: "Automated invoicing, expense tracking, AI-powered budget forecasting, and fraud detection for projects.",
        stage: "Idea Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const7/400/400",
        aiHint: "financial technology construction",
        rating: 0,
        enabled: true,
        href: "/construction-tech/construct-fin",
    },
    {
        id: 16,
        name: "Digital Twin Ops",
        description: "IoT platform for ongoing monitoring of building performance and predictive maintenance.",
        stage: "Idea Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const8/400/400",
        aiHint: "digital twin building",
        rating: 0,
        enabled: true,
        href: "/construction-tech/digital-twin",
    },
    {
        id: 17,
        name: "AeroSite AI (DaaS)",
        description: "Drone-as-a-Service for automated aerial surveys, progress tracking, and 3D terrain mapping.",
        stage: "Planning Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const9/400/400",
        aiHint: "construction drone survey",
        rating: 0,
        enabled: true,
        href: "/construction-tech/aerosite-ai",
    },
    {
        id: 18,
        name: "ClientView Portal",
        description: "White-label dashboards for clients to see live project status, track payment milestones, and manage warranties.",
        stage: "Idea Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const10/400/400",
        aiHint: "client dashboard project",
        rating: 0,
        enabled: true,
        href: "/construction-tech/client-view",
    },
    {
        id: 19,
        name: "AI Property Valuator",
        description: "Automates property appraisal using AI, considering location, size, amenities, and market trends for instant valuations.",
        stage: "Idea Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re1/400/400",
        aiHint: "property value graph",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/property-valuator",
    },
    {
        id: 20,
        name: "Smart Listing & Matching",
        description: "AI matches buyers/tenants with best-fit properties based on preferences, lifestyle, and budget, with automated lead routing to agents.",
        stage: "Idea Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re2/400/400",
        aiHint: "house search map",
        rating: 0,
        enabled: true
    },
    {
        id: 21,
        name: "3D Virtual Tour SaaS",
        description: "Offers 360° tours, AR/VR staging, and auto-generates furnished views of unfurnished properties.",
        stage: "Development Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re3/400/400",
        aiHint: "virtual reality home",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/virtual-tour",
    },
    {
        id: 22,
        name: "DocuChain Compliance",
        description: "Auto-generates sale agreements and tenancy contracts, tracking compliance with local laws and renewal dates.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re4/400/400",
        aiHint: "legal document agreement",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/docu-chain",
    },
    {
        id: 23,
        name: "SmartLease Manager",
        description: "Automates online rent collection, reminders, and late fee calculations, including tenant background checks.",
        stage: "Development Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re5/400/400",
        aiHint: "online payment rent",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/smart-lease-manager",
    },
    {
        id: 24,
        name: "InvestiSight AI",
        description: "Provides property ROI calculators, mortgage simulations, and rental yield forecasting with investment heatmaps.",
        stage: "Idea Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re6/400/400",
        aiHint: "investment analysis chart",
        rating: 0,
        enabled: true
    },
    {
        id: 25,
        name: "FacilityFlow SaaS",
        description: "A platform for tenants to raise service tickets, with auto-assignment to vendors and resolution tracking.",
        stage: "Idea Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re7/400/400",
        aiHint: "maintenance service ticket",
        rating: 0,
        enabled: true
    },
    {
        id: 26,
        name: "PropToken Platform",
        description: "Automates fractional property co-ownership via blockchain, with smart contracts for profit sharing and ownership transfer.",
        stage: "Idea Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re8/400/400",
        aiHint: "blockchain property ownership",
        rating: 0,
        enabled: true
    },
    {
        id: 27,
        name: "Tenant Digital Briefcase",
        description: "A one-stop app for users to manage their ID, contracts, utility bills, and insurance, with auto-reminders for renewals.",
        stage: "Idea Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re9/400/400",
        aiHint: "digital document wallet",
        rating: 0,
        enabled: true
    },
    {
        id: 28,
        name: "EcoBuild Certify",
        description: "Automated energy usage tracking, water consumption, and carbon footprint reporting for sustainability compliance.",
        stage: "Idea Phase",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re10/400/400",
        aiHint: "green building energy",
        rating: 0,
        enabled: true
    },
    {
        id: 29,
        name: "BoQ Generator",
        description: "Upload a floor plan and get an AI-generated preliminary Bill of Quantities for your project.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/re11/400/400",
        aiHint: "bill of quantities document",
        rating: 0,
        enabled: true,
        href: "/construction-tech/quantity-calculator",
    }
];
