

import type { Product } from './products.schema';

export const initialStoreProducts: Product[] = [
    {
        id: 1,
        name: "AI-Powered Smart Camera",
        description: "A high-resolution security camera with onboard AI for object detection and intelligent alerts.",
        stage: "Live & Operating",
        category: "Electronics",
        price: 79.900,
        image: "https://images.unsplash.com/photo-1588052163994-b3d5b9b8c253?q=80&w=600&auto=format&fit=crop",
        aiHint: "smart camera",
        rating: 4.8,
        enabled: true,
        adminStatus: 'Completed',
    },
    {
        id: 2,
        name: "VR Headset 'PANOSPACE'",
        description: "Experience immersive virtual reality with our flagship VR headset, PANOSPACE. Perfect for gaming, virtual tours, and professional training.",
        stage: "Live & Operating",
        category: "Electronics",
        price: 189.900,
        image: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?q=80&w=600&auto=format&fit=crop",
        aiHint: "vr headset",
        rating: 4.9,
        enabled: true,
        adminStatus: 'Completed',
    }
];

export const initialProducts: Product[] = [
    {
        id: 1,
        name: "PANOSPACE",
        description: "Immersive platform for virtual tours.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?q=80&w=600&auto=format&fit=crop",
        aiHint: "vr headset",
        rating: 4.9,
        enabled: true,
        adminStatus: 'Completed',
        href: "/real-estate-tech/virtual-tour",
    },
    {
        id: 2,
        name: "ameen",
        description: "A secure digital identity and authentication solution, expanding into a Smart Lost & Found Solution App.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://images.unsplash.com/photo-1584433144859-1fc3ab64a957?q=80&w=600&auto=format&fit=crop",
        aiHint: "digital security",
        rating: 4.7,
        enabled: true,
        adminStatus: 'Completed',
        href: "/ameen",
    },
    {
        id: 3,
        name: "APPI – عـبِّـي",
        description: "An innovative mobile application that leverages AI/Deeptech and IoT to provide real-time, personalized insights into household utility consumption.",
        stage: "In Development",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://images.unsplash.com/photo-1619498114959-a1b63c6a4697?q=80&w=600&auto=format&fit=crop",
        aiHint: "smart home",
        rating: 0,
        enabled: true,
        adminStatus: 'On Track',
        href: "/appi",
    },
    {
        id: 4,
        name: "KHIDMA",
        description: "A revolutionary AI/Deep-tech powered mobile application that acts as a dynamic marketplace connecting service seekers with qualified providers.",
        stage: "In Development",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://images.unsplash.com/photo-1581092918056-0c9c991e6024?q=80&w=600&auto=format&fit=crop",
        aiHint: "marketplace app",
        rating: 0,
        enabled: true,
        adminStatus: 'On Track',
        href: "/khidma",
    },
    {
        id: 5,
        name: "VMALL",
        description: "A revolutionary Web & Mobile application that leverages VR and AR to create immersive shopping experiences.",
        stage: "In Development",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?q=80&w=600&auto=format&fit=crop",
        aiHint: "virtual shopping",
        rating: 0,
        enabled: true,
        adminStatus: 'On Track',
        href: "/vmall",
    },
     {
        id: 6,
        name: "BidWise Estimator",
        description: "Automated cost estimation (material, labor, equipment) and tender management platform with dynamic pricing.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=600&auto=format&fit=crop",
        aiHint: "construction planning",
        rating: 4.8,
        enabled: true,
        adminStatus: 'Completed',
        href: "/construction-tech/bid-estimator",
    },
    {
        id: 7,
        name: "AI Property Valuator",
        description: "Automates property appraisal using AI, considering location, size, amenities, and market trends for instant valuations.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=600&auto=format&fit=crop",
        aiHint: "real estate",
        rating: 4.7,
        enabled: true,
        adminStatus: 'Completed',
        href: "/real-estate-tech/property-valuator",
    },
     {
        id: 8,
        name: "DocuChain Compliance",
        description: "Auto-generates sale agreements and tenancy contracts, tracking compliance with local laws and renewal dates.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1564757262529-af3a7ad47943?q=80&w=600&auto=format&fit=crop",
        aiHint: "legal document",
        rating: 4.9,
        enabled: true,
        adminStatus: 'Completed',
        href: "/real-estate-tech/docu-chain"
    },
    {
        id: 9,
        name: "SmartLease Manager",
        description: "Automates online rent collection, reminders, and late fee calculations, including tenant background checks.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1600880292210-252c8a0a4a84?q=80&w=600&auto=format&fit=crop",
        aiHint: "property management",
        rating: 4.6,
        enabled: true,
        adminStatus: 'Completed',
        href: "/real-estate-tech/smart-lease-manager"
    },
    {
        id: 10,
        name: "InvestiSight AI",
        description: "Provides property ROI calculators, mortgage simulations, and rental yield forecasting with investment heatmaps.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1554224155-8d04421cd6c3?q=80&w=600&auto=format&fit=crop",
        aiHint: "financial analysis",
        rating: 4.5,
        enabled: true,
        adminStatus: 'Completed',
        href: "/real-estate-tech/investisight"
    },
    {
        id: 11,
        name: "EduFlow Suite",
        description: "An all-in-one administrative automation platform for schools, featuring smart timetabling and automated admissions.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop",
        aiHint: "university campus",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/education-tech/eduflow",
    },
    {
        id: 12,
        name: "CognitaLearn",
        description: "A personalized adaptive learning platform that uses AI to create custom learning paths and gamified modules.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1491841550275-5b462bf48366?q=80&w=600&auto=format&fit=crop",
        aiHint: "focused student",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/education-tech/cognita-learn",
    },
    {
        id: 13,
        name: "Guardian AI",
        description: "A student wellbeing and success platform offering risk profiling, AI career advisory, and mental health support.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?q=80&w=600&auto=format&fit=crop",
        aiHint: "support group",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/education-tech/guardian-ai",
    },
    {
        id: 14,
        name: "CertiTrust",
        description: "A blockchain-based digital credentialing system combined with AI proctoring for secure, verifiable certificates.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?q=80&w=600&auto=format&fit=crop",
        aiHint: "blockchain security",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/education-tech/certitrust",
    },
    {
        id: 15,
        name: "CampusOS",
        description: "A smart campus management platform leveraging IoT for energy efficiency, space optimization, and predictive maintenance.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1607503328578-5775b394e1b8?q=80&w=600&auto=format&fit=crop",
        aiHint: "modern building",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/education-tech/campus-os",
    },
     {
        id: 16,
        name: "BoQ Generator",
        description: "Upload a floor plan and get an AI-generated preliminary Bill of Quantities for your project.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1519756301029-33a5b0452926?q=80&w=600&auto=format&fit=crop",
        aiHint: "architectural blueprints",
        rating: 4.8,
        enabled: true,
        adminStatus: "Completed",
        href: "/construction-tech/quantity-calculator",
    },
     {
        id: 17,
        name: "Fire & Safety Estimator",
        description: "Upload a floor plan and let our AI generate a preliminary list of fire safety equipment and an initial cost estimate.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1617997572343-24156d491a5e?q=80&w=600&auto=format&fit=crop",
        aiHint: "fire safety",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/construction-tech/fire-safety-estimator",
    },
     {
        id: 18,
        name: "SiteGuard Compliance",
        description: "Mobile safety inspection app with AI image recognition for PPE violations and automated permit tracking.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1550977875-a8536b35e848?q=80&w=600&auto=format&fit=crop",
        aiHint: "safety helmet",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/construction-tech/site-guard",
    },
     {
        id: 19,
        name: "WorkforceFlow",
        description: "AI-driven workforce scheduling, digital timecards, and IoT equipment tracking to optimize your construction site operations.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1581092918056-0c9c991e6024?q=80&w=600&auto=format&fit=crop",
        aiHint: "construction workers",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/construction-tech/workforce-scheduler",
    },
    {
        id: 20,
        name: "FacilityFlow SaaS",
        description: "A streamlined platform for tenants to raise service tickets, with auto-assignment to vendors and resolution tracking.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?q=80&w=600&auto=format&fit=crop",
        aiHint: "technician working",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/real-estate-tech/facility-flow",
    },
    {
        id: 21,
        name: "AeroSite AI (DaaS)",
        description: "Drone-as-a-Service for automated aerial surveys, progress tracking, and 3D terrain mapping.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1519672102930-99a6a1f1035b?q=80&w=600&auto=format&fit=crop",
        aiHint: "drone construction",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/construction-tech/aero-site",
    },
    {
        id: 22,
        name: "Digital Twin Ops",
        description: "IoT platform for ongoing monitoring of building performance and predictive maintenance.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1621935579841-381442188a8c?q=80&w=600&auto=format&fit=crop",
        aiHint: "server room",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/construction-tech/digital-twin",
    },
    {
        id: 23,
        name: "EcoBuild Certify",
        description: "Automated energy usage tracking, water consumption, and carbon footprint reporting for sustainability compliance.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?q=80&w=600&auto=format&fit=crop",
        aiHint: "green building",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/real-estate-tech/ecobuild-certify",
    },
     {
        id: 24,
        name: "PropToken Platform",
        description: "Automates fractional property co-ownership via blockchain, with smart contracts for profit sharing and ownership transfer.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1639322537228-f710d846310a?q=80&w=600&auto=format&fit=crop",
        aiHint: "blockchain technology",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/real-estate-tech/proptoken-platform",
    },
    {
        id: 25,
        name: "Tenant Digital Briefcase",
        description: "A one-stop app for users to manage their ID, contracts, utility bills, and insurance, with auto-reminders for renewals.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1560520655-5431d102a28c?q=80&w=600&auto=format&fit=crop",
        aiHint: "document management",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/real-estate-tech/tenant-briefcase",
    },
    {
        id: 26,
        name: "AI Scholarship Finder",
        description: "An AI-powered tool that searches the web for scholarship opportunities based on a student's field of study and academic level.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=600&auto=format&fit=crop",
        aiHint: "graduation cap",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/education-tech/scholarships",
    },
     {
        id: 27,
        name: "Teacher Toolkit",
        description: "A suite of tools for educators, including a Lesson Gamifier to convert textbooks into interactive content, flashcards, and presentations.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=600&auto=format&fit=crop",
        aiHint: "teacher classroom",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/education-tech/lesson-gamifier",
    },
     {
        id: 28,
        name: "AlumniConnect",
        description: "A comprehensive digital platform for universities to engage their alumni network, fostering connections and professional opportunities.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=600&auto=format&fit=crop",
        aiHint: "university alumni",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/education-tech/alumni-connect",
    },
    {
        id: 29,
        name: "AI Interior Designer",
        description: "Upload a photo of your room and get instant interior design ideas powered by AI.",
        stage: "Live & Operating",
        category: "AI & Creative Tools",
        price: 0,
        image: "https://images.unsplash.com/photo-1618220179428-22790b461013?q=80&w=600&auto=format&fit=crop",
        aiHint: "modern living room",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/interior-designer"
    },
    {
        id: 30,
        name: "AI PDF Form Filler",
        description: "Upload any PDF form and let our AI intelligently fill it out based on your profile data.",
        stage: "Live & Operating",
        category: "AI & Creative Tools",
        price: 0,
        image: "https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?q=80&w=600&auto=format&fit=crop",
        aiHint: "form document",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/pdf-form-filler"
    },
    {
        id: 31,
        name: "ProcureChain SaaS",
        description: "An e-procurement platform with automated vendor approvals, asset rentals, and predictive ordering.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1578575437136-7242e38d7525?q=80&w=600&auto=format&fit=crop",
        aiHint: "supply chain logistics",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/construction-tech/procurechain",
    },
     {
        id: 32,
        name: "DriveSync AI",
        description: "An AI-powered SaaS platform for car rental agencies, featuring an intelligent booking agent, fleet management, and integration with IVMS (In-Vehicle Monitoring Systems) for real-time tracking.",
        stage: "Live & Operating",
        category: "Automotive Tech",
        price: 0,
        image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=600&auto=format&fit=crop",
        aiHint: "sports car",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/drivesync-ai",
    },
     {
        id: 33,
        name: "Beauty & Wellness Hub",
        description: "A complete SaaS solution for salons, spas, and barbershops to manage appointments, staff, services, and client relationships.",
        stage: "Live & Operating",
        category: "Beauty & Wellness",
        price: 0,
        image: "https://images.unsplash.com/photo-1632345031435-8727f6897d53?q=80&w=600&auto=format&fit=crop",
        aiHint: "salon interior",
        rating: 0,
        enabled: true,
        adminStatus: "Completed",
        href: "/beauty-hub",
    },
];

