
export interface Product {
    id: number;
    name: string;
    description: string;
    stage: string;
    category: string;
    price: number;
    image: string;
    aiHint: string;
    rating: number;
    enabled: boolean;
    href?: string;
    adminStatus?: 'On Track' | 'At Risk' | 'On Hold' | 'Completed';
    adminNotes?: string;
}

export const initialProducts: Product[] = [
    {
        id: 9,
        name: "Smart PM SaaS",
        description: "AI-based scheduling, Gantt charts, resource allocation, real-time collaboration, and document management.",
        stage: "Development Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const1/400/400",
        aiHint: "construction management software",
        rating: 0,
        enabled: true,
        href: "/admin/projects",
        adminStatus: 'Completed',
        adminNotes: "Core features are live in the admin panel's Projects page."
    },
    {
        id: 10,
        name: "BidWise Estimator",
        description: "Automated cost estimation (material, labor, equipment) and tender management platform with dynamic pricing.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const2/400/400",
        aiHint: "construction bidding document",
        rating: 0,
        enabled: true,
        href: "/construction-tech/bid-estimator",
        adminStatus: 'Completed',
        adminNotes: "User acceptance testing is underway with pilot partners."
    },
     {
        id: 11,
        name: "SiteGuard Compliance",
        description: "Mobile safety inspection app with AI image recognition for PPE violations and automated permit tracking.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const4/400/400",
        aiHint: "construction safety compliance",
        rating: 0,
        enabled: true,
        href: "/construction-tech/site-guard",
        adminStatus: 'Completed',
        adminNotes: "Live and functional. PPE detection model has a 92% accuracy rate."
    },
    {
        id: 12,
        name: "Fire & Safety Estimator",
        description: "AI-powered tool to analyze floor plans and generate cost estimates and equipment lists for fire alarm and firefighting systems.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/fire-safety/400/400",
        aiHint: "fire alarm system",
        rating: 0,
        enabled: true,
        href: "/construction-tech/fire-safety-estimator",
        adminStatus: "Completed",
    },
    {
        id: 13,
        name: "WorkforceFlow",
        description: "AI-driven workforce scheduling, digital timecards with face recognition, and IoT equipment tracking.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const5/400/400",
        aiHint: "construction workforce management",
        rating: 0,
        enabled: true,
        href: "/construction-tech/workforce-scheduler",
        adminStatus: 'Completed',
        adminNotes: "The AI Workforce Scheduler is live and functional."
    },
    {
        id: 14,
        name: "ProcureChain SaaS",
        description: "E-procurement platform with automated vendor approvals, asset rentals, and predictive ordering.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const6/400/400",
        aiHint: "supply chain logistics",
        rating: 0,
        enabled: true,
        href: "/construction-tech/asset-rentals",
        adminStatus: 'Completed',
        adminNotes: "Asset rental feature is live. Predictive ordering and blockchain are on hold."
    },
    {
        id: 15,
        name: "ConstructFin",
        description: "Automated invoicing, expense tracking, AI-powered budget forecasting, and fraud detection for projects.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const7/400/400",
        aiHint: "financial technology construction",
        rating: 0,
        enabled: true,
        href: "/cfo",
        adminStatus: 'Completed',
        adminNotes: "CFO Dashboard and AI Audit features are live."
    },
    {
        id: 16,
        name: "Digital Twin Ops",
        description: "IoT platform for ongoing monitoring of building performance and predictive maintenance. (Conceptual - Requires hardware integration)",
        stage: "Idea Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const8/400/400",
        aiHint: "digital twin building",
        rating: 0,
        enabled: true,
        href: "/measurement-analyzer",
        adminStatus: 'On Track',
        adminNotes: "This feature requires hardware (IoT) integration and is on hold for the prototype."
    },
    {
        id: 17,
        name: "AeroSite AI (DaaS)",
        description: "Drone-as-a-Service for automated aerial surveys, progress tracking, and 3D terrain mapping. (Conceptual - Requires hardware integration)",
        stage: "Development Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const9/400/400",
        aiHint: "construction drone survey",
        rating: 0,
        enabled: false,
        adminStatus: 'At Risk',
        adminNotes: "This feature requires hardware (drone) integration and is on hold for the prototype."
    },
    {
        id: 18,
        name: "ClientView Portal",
        description: "White-label dashboards for clients to see live project status, track payment milestones, and manage warranties.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const10/400/400",
        aiHint: "client dashboard project",
        rating: 0,
        enabled: true,
        href: "/admin/projects",
        adminStatus: 'Completed',
        adminNotes: "Core features (Kanban, AI Inception) are live in the admin panel."
    },
    {
        id: 19,
        name: "AI Property Valuator",
        description: "Automates property appraisal using AI, considering location, size, amenities, and market trends for instant valuations.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re1/400/400",
        aiHint: "property value graph",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/property-valuator",
        adminStatus: 'Completed',
        adminNotes: "Service is live and performing within expected parameters."
    },
    {
        id: 20,
        name: "Smart Listing & Matching",
        description: "AI matches buyers/tenants with best-fit properties based on preferences, lifestyle, and budget, with automated lead routing to agents.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re2/400/400",
        aiHint: "house search map",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/smart-listing",
        adminStatus: 'Completed',
        adminNotes: "Core matching algorithm is complete. Now working on the agent dashboard."
    },
    {
        id: 21,
        name: "3D Virtual Tour SaaS",
        description: "Upload a 2D floor plan and generate a multi-room virtual tour with stunning 3D architectural renderings in any style.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re3/400/400",
        aiHint: "virtual reality home",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/virtual-tour",
        adminStatus: 'Completed',
        adminNotes: "Public launch scheduled for next month. Marketing campaign is active."
    },
    {
        id: 22,
        name: "DocuChain Compliance",
        description: "Auto-generates sale agreements and tenancy contracts, tracking compliance with local laws and renewal dates.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re4/400/400",
        aiHint: "legal document agreement",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/docu-chain",
        adminStatus: 'Completed',
        adminNotes: "Service is live. Monitoring for user feedback on contract templates."
    },
    {
        id: 23,
        name: "SmartLease Manager",
        description: "Automates online rent collection, reminders, and late fee calculations, including tenant background checks.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re5/400/400",
        aiHint: "online payment rent",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/smart-lease-manager",
        adminStatus: 'Completed',
        adminNotes: "Stable and operational. No major issues reported."
    },
    {
        id: 24,
        name: "InvestiSight AI",
        description: "Provides property ROI calculators, mortgage simulations, and rental yield forecasting with investment heatmaps.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re6/400/400",
        aiHint: "investment analysis chart",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/investisight",
        adminStatus: 'Completed',
        adminNotes: "Initial version with ROI and Mortgage calculators is now live."
    },
    {
        id: 25,
        name: "FacilityFlow SaaS",
        description: "A streamlined platform for tenants to raise service tickets, with auto-assignment to vendors and resolution tracking.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re7/400/400",
        aiHint: "maintenance service ticket",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/facility-flow",
        adminStatus: 'Completed',
        adminNotes: "Finalizing technical specifications and architecture design."
    },
    {
        id: 26,
        name: "PropToken Platform",
        description: "Automates fractional property co-ownership via blockchain, with smart contracts for profit sharing and ownership transfer.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re8/400/400",
        aiHint: "blockchain property ownership",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/proptoken-platform",
        adminStatus: 'Completed',
        adminNotes: "Assessing legal and regulatory hurdles for tokenization in the region."
    },
    {
        id: 27,
        name: "Tenant Digital Briefcase",
        description: "A one-stop app for users to manage their ID, contracts, utility bills, and insurance, with auto-reminders for renewals.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re9/400/400",
        aiHint: "digital document wallet",
        rating: 0,
        enabled: true,
        href: "/briefcase",
        adminStatus: 'Completed',
        adminNotes: "Concept is solid. Needs a dedicated project manager to move forward."
    },
    {
        id: 28,
        name: "EcoBuild Certify",
        description: "Automated energy usage tracking, water consumption, and carbon footprint reporting for sustainability compliance.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/re10/400/400",
        aiHint: "green building energy",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/ecobuild-certify",
        adminStatus: 'Completed',
        adminNotes: "Awaiting government regulations on green building standards before proceeding."
    },
    {
        id: 29,
        name: "BoQ Generator",
        description: "Upload a floor plan and get an AI-generated preliminary Bill of Quantities for your project.",
        stage: "Live & Operating",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/re11/400/400",
        aiHint: "bill of quantities document",
        rating: 0,
        enabled: true,
        href: "/construction-tech/quantity-calculator",
        adminStatus: 'Completed',
        adminNotes: "Live and integrated with the main construction tech portal."
    },
    {
        id: 30,
        name: "AI Interior Designer",
        description: "Get instant interior design ideas. Upload a photo of your room, describe the style you want, and let our AI generate a stunning new design concept for you.",
        stage: "Live & Operating",
        category: "AI & Creative Tools",
        price: 0,
        image: "https://picsum.photos/seed/re12/400/400",
        aiHint: "modern living room",
        rating: 0,
        enabled: true,
        href: "/interior-designer",
        adminStatus: 'Completed',
        adminNotes: "Feature is popular. Consider expanding with furniture shopping integration."
    },
    {
        id: 31,
        name: "AI PDF Form Filler",
        description: "Upload any PDF form (bank, school, visa) and let our AI intelligently fill it out based on your profile data, saving you time and effort.",
        stage: "Live & Operating",
        category: "AI & Creative Tools",
        price: 0,
        image: "https://picsum.photos/seed/formfiller/400/400",
        aiHint: "pdf document form",
        rating: 0,
        enabled: true,
        href: "/pdf-form-filler",
        adminStatus: "Completed",
        adminNotes: "Service is live and ready for public use.",
    },
    {
        id: 32,
        name: "AlumniConnect",
        description: "A comprehensive digital platform for universities, colleges, and schools to engage their alumni network, fostering connections and professional opportunities.",
        stage: "Research Phase",
        category: "SaaS",
        price: 0,
        image: "https://picsum.photos/seed/alumni/400/400",
        aiHint: "university alumni network",
        rating: 0,
        enabled: false,
        adminStatus: 'On Track',
        adminNotes: "Market research in progress to identify target institutions."
    },
    {
        id: 33,
        name: "Hadeeya",
        description: "A sophisticated prepaid digital gift card platform, enabling seamless and personalized gifting experiences for individuals and corporate clients.",
        stage: "Research Phase",
        category: "Fintech",
        price: 0,
        image: "https://picsum.photos/seed/giftcard/400/400",
        aiHint: "digital gift card",
        rating: 0,
        enabled: false,
        adminStatus: 'On Track',
        adminNotes: "Assessing potential merchant partnerships."
    },
    {
        id: 34,
        name: "AI-POS for Education",
        description: "A smart, AI-driven Point-of-Sale system for university canteens or school stores, featuring inventory management, sales analytics, and student spending insights.",
        stage: "Live & Operating",
        category: "SaaS",
        price: 0,
        image: "https://picsum.photos/seed/pos/400/400",
        aiHint: "point of sale system",
        rating: 0,
        enabled: true,
        href: "/cfo",
        adminStatus: 'Completed',
        adminNotes: "Evaluating hardware requirements and potential suppliers."
    },
    {
        id: 35,
        name: "EduFlow Suite",
        description: "An all-in-one administrative automation platform for schools, featuring smart timetabling and automated admissions workflows.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://picsum.photos/seed/eduflow/400/400",
        aiHint: "education administration software",
        rating: 0,
        enabled: true,
        adminStatus: 'Completed',
        adminNotes: "Generated from Education Playbook. Addresses Pillar 1: Administration & Operations.",
        href: "/education-tech/eduflow",
    },
    {
        id: 36,
        name: "CognitaLearn",
        description: "A personalized adaptive learning platform that uses AI to create custom learning paths, gamified modules, and automated grading for students.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://picsum.photos/seed/cognita/400/400",
        aiHint: "personalized learning ai",
        rating: 0,
        enabled: true,
        adminStatus: 'Completed',
        adminNotes: "Generated from Education Playbook. Addresses Pillar 2: Teaching & Learning Innovation.",
        href: "/education-tech/cognita-learn"
    },
    {
        id: 37,
        name: "Guardian AI",
        description: "A student success platform offering risk profiling, AI career advisory & interview coaching, and wellbeing support.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://picsum.photos/seed/guardian/400/400",
        aiHint: "student success wellbeing",
        rating: 0,
        enabled: true,
        adminStatus: 'Completed',
        adminNotes: "Generated from Education Playbook. Addresses Pillar 3: Student Experience & Wellbeing.",
        href: "/education-tech/guardian-ai",
    },
    {
        id: 38,
        name: "CertiTrust",
        description: "A blockchain-based digital credentialing system combined with AI proctoring to ensure the integrity of exams and provide secure, verifiable certificates.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://picsum.photos/seed/certitrust/400/400",
        aiHint: "blockchain certificate security",
        rating: 0,
        enabled: true,
        adminStatus: 'Completed',
        adminNotes: "Generated from Education Playbook. Addresses Pillar 4: Exams, Assessments & Certification.",
        href: "/education-tech/certitrust",
    },
    {
        id: 39,
        name: "CampusOS",
        description: "A smart campus management platform leveraging IoT for energy efficiency, space optimization, and predictive maintenance for a sustainable and cost-effective campus.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://picsum.photos/seed/campusos/400/400",
        aiHint: "smart campus iot",
        rating: 0,
        enabled: true,
        adminStatus: 'Completed',
        adminNotes: "Generated from Education Playbook. Addresses Pillar 9: Infrastructure & Campus Management.",
        href: "/education-tech/campus-os",
    },
    {
        id: 40,
        name: "AI Scholarship Finder",
        description: "An AI-powered tool that searches the web for scholarship opportunities based on a student's field of study and academic level.",
        stage: "Live & Operating",
        category: "Education Tech",
        price: 0,
        image: "https://picsum.photos/seed/scholarship/400/400",
        aiHint: "scholarship document graduation",
        rating: 0,
        enabled: true,
        href: "/education-tech/guardian-ai",
        adminStatus: "Completed",
    },
    {
        id: 1,
        name: "ameen",
        description: "A secure digital identity solution and smart home control panel. Log in with WhatsApp OTP and manage IoT devices like smart locks.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://images.unsplash.com/photo-1615552319349-43a15a81d4b2?q=80&w=1920&auto=format&fit=crop",
        aiHint: "digital identity security",
        rating: 0,
        enabled: true,
        href: "/ameen",
        adminStatus: "Completed",
    },
    {
        id: 11,
        name: "StructurAI BIM",
        description: "AI-powered BIM for automated clash detection and material optimization. (Conceptual - Requires specialized backend).",
        stage: "Planning Phase",
        category: "Construction Tech",
        price: 0,
        image: "https://picsum.photos/seed/const3/400/400",
        aiHint: "building information modeling",
        rating: 0,
        enabled: false,
        adminStatus: 'On Hold',
        adminNotes: "This feature requires complex backend processing for BIM/CAD files and is on hold for the prototype."
    },
    {
        id: 43,
        name: "RAAHA",
        description: "An AI-powered, white-label SaaS platform for domestic workforce agencies to streamline recruitment, management, and client communication.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://picsum.photos/seed/raaha/400/400",
        aiHint: "workforce management platform",
        rating: 0,
        enabled: true,
        href: "/raaha",
        adminStatus: "Completed"
    },
    {
        id: 44,
        name: "StairSpace",
        description: "A marketplace that turns unused under-stair spaces into rentable micro-business spots for individuals and small businesses.",
        stage: "Live & Operating",
        category: "Real Estate Tech",
        price: 0,
        image: "https://picsum.photos/seed/stairspace/400/400",
        aiHint: "staircase retail pop-up",
        rating: 0,
        enabled: true,
        href: "/real-estate-tech/stairspace",
        adminStatus: "Completed"
    },
     {
        id: 45,
        name: "Tender Response Assistant",
        description: "Upload tender documents and let our AI generate a comprehensive, professional draft response tailored to your company's strengths.",
        stage: "Live & Operating",
        category: "AI & Creative Tools",
        price: 0,
        image: "https://picsum.photos/seed/tender-response/400/400",
        aiHint: "legal document tender",
        rating: 0,
        enabled: true,
        href: "/tender-assistant",
        adminStatus: "Completed"
    },
    {
        id: 46,
        name: "Business Hub",
        description: "A B2B marketplace connecting businesses with each other and with new clients for opportunities.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://picsum.photos/seed/business-hub/400/400",
        aiHint: "business network connection",
        rating: 4.8,
        enabled: true,
        href: "/business-hub",
        adminStatus: "Completed",
    },
    {
        id: 47,
        name: "Community Hub",
        description: "A digital platform for expatriate communities and charities to manage their own affairs, elections, and events.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://picsum.photos/seed/community-hub/400/400",
        aiHint: "community people gathering",
        rating: 4.7,
        enabled: true,
        href: "/community-hub",
        adminStatus: "Completed",
    },
    {
        id: 48,
        name: "DriveSync AI",
        description: "An AI-powered SaaS platform for car rental agencies, featuring an intelligent booking agent, fleet management, and integration with IVMS for real-time tracking.",
        stage: "Live & Operating",
        category: "Automotive Tech",
        price: 0,
        image: "https://picsum.photos/seed/drivesync/400/400",
        aiHint: "car rental dashboard",
        rating: 0,
        enabled: true,
        href: "/drivesync-ai",
        adminStatus: "Completed",
    },
    {
        id: 49,
        name: "AI SEO Analyzer",
        description: "Get on-page SEO analysis and actionable recommendations for any webpage.",
        stage: "Live & Operating",
        category: "AI & Creative Tools",
        price: 0,
        image: "https://picsum.photos/seed/seo-analyzer/400/400",
        aiHint: "search engine optimization",
        rating: 0,
        enabled: true,
        href: "/seo-analyzer",
        adminStatus: "Completed",
    },
    {
        id: 50,
        name: "VEO Video Factory",
        description: "Generate high-quality video clips from a simple text description using Google's Veo model.",
        stage: "Live & Operating",
        category: "AI & Creative Tools",
        price: 0,
        image: "https://picsum.photos/seed/video-factory/400/400",
        aiHint: "video production film",
        rating: 0,
        enabled: true,
        href: "/video-generator",
        adminStatus: "Completed",
    },
    {
        id: 51,
        name: "StockClear",
        description: "B2B marketplace for wholesalers and retailers to liquidate excess or near-expiry stock through auctions and bulk sales.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://picsum.photos/seed/stockclear/400/400",
        aiHint: "warehouse boxes inventory",
        rating: 0,
        enabled: true,
        href: "/stock-clear",
        adminStatus: "Completed"
    },
    {
        id: 52,
        name: "KHIDMA",
        description: "A revolutionary AI-powered mobile application that transforms the traditional service industry. It acts as a dynamic marketplace connecting service seekers with qualified providers through an innovative auction and tender system.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://picsum.photos/seed/khidma/400/400",
        aiHint: "service marketplace app",
        rating: 0,
        enabled: true,
        href: "/khidma",
        adminStatus: "Completed"
    },
    {
        id: 53,
        name: "GENIUS Career Platform",
        description: "An end-to-end AI career coach that helps job seekers optimize their CVs for modern Applicant Tracking Systems (ATS) and prepare for interviews with confidence.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://picsum.photos/seed/genius-platform/400/400",
        aiHint: "career coaching cv",
        rating: 0,
        enabled: true,
        href: "/cv-enhancer",
        adminStatus: "Completed",
    },
    {
        id: 54,
        name: "VMALL",
        description: "A revolutionary Web & Mobile application that leverages VR and AR to create immersive shopping experiences.",
        stage: "Live & Operating",
        category: "General Platforms & SaaS",
        price: 0,
        image: "https://picsum.photos/seed/vmall/400/400",
        aiHint: "virtual reality shopping",
        rating: 0,
        enabled: true,
        href: "/vmall",
        adminStatus: "Completed",
    },
];

// This is where e-commerce products should live in a real application,
// separate from the company's internal projects.
export const initialStoreProducts: Product[] = [
    {
        id: 1,
        name: "Wireless Headphones",
        description: "High-fidelity audio with noise cancellation.",
        stage: "Live & Operating",
        category: "Electronics",
        price: 1.3,
        image: "https://picsum.photos/seed/p1/400/400",
        aiHint: "headphones product",
        rating: 4.5,
        enabled: true,
        adminStatus: 'Completed',
    },
    {
        id: 2,
        name: "Modern Coffee Table",
        description: "Oak wood with a minimalist design for modern living.",
        stage: "Live & Operating",
        category: "Home Goods",
        price: 2.5,
        image: "https://picsum.photos/seed/p2/400/400",
        aiHint: "coffee table",
        rating: 4.8,
        enabled: true,
        adminStatus: 'Completed',
    },
    {
        id: 3,
        name: "Performance Running Shoes",
        description: "Lightweight and responsive for your daily run.",
        stage: "Live & Operating",
        category: "Sports",
        price: 0.9,
        image: "https://picsum.photos/seed/p3/400/400",
        aiHint: "running shoes",
        rating: 4.7,
        enabled: true,
        adminStatus: 'Completed',
    },
    {
        id: 4,
        name: "Organic Cotton T-Shirt",
        description: "Soft, breathable, and sustainably made.",
        stage: "Live & Operating",
        category: "Apparel",
        price: 0.25,
        image: "https://picsum.photos/seed/p4/400/400",
        aiHint: "cotton t-shirt",
        rating: 4.9,
        enabled: true,
        adminStatus: 'Completed',
    },
     {
        id: 5,
        name: "Smartwatch Series 8",
        description: "Track your fitness and stay connected on the go.",
        stage: "Live & Operating",
        category: "Electronics",
        price: 4.0,
        image: "https://picsum.photos/seed/p5/400/400",
        aiHint: "smartwatch product",
        rating: 4.9,
        enabled: true,
        adminStatus: 'Completed',
    },
    {
        id: 6,
        name: "Leather Backpack",
        description: "Stylish and durable for work or travel.",
        stage: "Live & Operating",
        category: "Apparel",
        price: 1.5,
        image: "https://picsum.photos/seed/p6/400/400",
        aiHint: "leather backpack",
        rating: 4.6,
        enabled: true,
        adminStatus: 'Completed',
    },
    {
        id: 7,
        name: "Non-stick Cookware Set",
        description: "A complete set for all your cooking needs.",
        stage: "Live & Operating",
        category: "Home Goods",
        price: 2.0,
        image: "https://picsum.photos/seed/p7/400/400",
        aiHint: "cookware set",
        rating: 4.7,
        enabled: true,
        adminStatus: 'Completed',
    },
    {
        id: 8,
        name: "The Alchemist",
        description: "A bestselling novel by Paulo Coelho.",
        stage: "Live & Operating",
        category: "Books",
        price: 0.13,
        image: "https://picsum.photos/seed/p8/400/400",
        aiHint: "book cover",
        rating: 4.8,
        enabled: true,
        adminStatus: 'Completed',
    },
];

  
