
import type { Property } from './properties.schema';

export const initialProperties: Property[] = [
  {
    id: 'prop_01',
    title: 'Luxury 4-Bedroom Villa in Al Mouj',
    listingType: 'For Sale',
    propertyType: 'Villa',
    location: 'Al Mouj, Muscat',
    price: 350000,
    bedrooms: 4,
    bathrooms: 5,
    areaSqM: 450,
    description: 'A stunning modern villa with a private pool, garden, and direct marina access. Features high-end finishes and a spacious open-plan living area.',
    status: 'Available',
    buildingAge: '3 years',
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=800&auto=format&fit=crop',
    aiHint: 'modern villa exterior',
  },
  {
    id: 'prop_02',
    title: 'Spacious 2-Bedroom Apartment',
    listingType: 'For Rent',
    propertyType: 'Apartment',
    location: 'Qurum, Muscat',
    price: 650,
    bedrooms: 2,
    bathrooms: 2,
    areaSqM: 140,
    description: 'A bright and airy apartment in a prime location, close to the beach and shopping malls. Includes access to a shared pool and gym.',
    status: 'Available',
    buildingAge: '5 years',
    imageUrl: 'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?q=80&w=800&auto=format&fit=crop',
    aiHint: 'apartment building exterior',
  },
  {
    id: 'prop_03',
    title: 'Brand New Townhouse in Shatti Al Qurum',
    listingType: 'For Sale',
    propertyType: 'Townhouse',
    location: 'Shatti Al Qurum, Muscat',
    price: 180000,
    bedrooms: 3,
    bathrooms: 4,
    areaSqM: 220,
    description: 'A newly constructed townhouse with modern architecture and smart home features, located in a prestigious neighborhood.',
    status: 'Sold',
    buildingAge: 'New',
    imageUrl: 'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?q=80&w=800&auto=format&fit=crop',
    aiHint: 'modern townhouse exterior',
  },
];
