
export interface Provider {
  id: string;
  name: string;
  email: string;
  services: string;
  status: 'Vetted' | 'Pending Review' | 'On Hold';
  portfolio?: string;
  notes?: string;
}

export const initialProviders: Provider[] = [
    {
        id: "prov_1",
        name: "Creative Solutions LLC",
        email: "contact@creativesolutions.io",
        services: "Web Development, UI/UX Design",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Reliable partner for several past projects. Excellent at React.",
    },
    {
        id: "prov_2",
        name: "Jane Doe Graphics",
        email: "jane.doe@gmail.com",
        services: "Branding, Logo Design, Illustration",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Winner of the last re-branding competition. Great creative eye.",
    },
    {
        id: "prov_3",
        name: "Muscat Tech Experts",
        email: "info@muscat-tech.om",
        services: "IT Support, Cloud Migration",
        status: "Pending Review",
        portfolio: "https://example.com",
        notes: "New application received on 2024-07-28.",
    },
    {
        id: "prov_4",
        name: "Ali Al-Farsi",
        email: "ali.farsi.dev@proton.me",
        services: "Python, AI/ML, Data Scraping",
        status: "Pending Review",
        notes: "Specializes in backend services for AI. Seems promising.",
    },
    {
        id: "prov_5",
        name: "Global Voiceovers",
        email: "talent@globalvoiceovers.com",
        services: "Voice Acting, Audio Production",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Provided voice work for the Voxi agent.",
    },
    {
        id: "prov_6",
        name: "Nasser Al-Habsi",
        email: "nasser.habsi@oman.net",
        services: "AR/VR Development (Unity)",
        status: "On Hold",
        portfolio: "https://example.com",
        notes: "Currently on another long-term project. Re-evaluate in Q4.",
    },
    {
        id: "prov_7",
        name: "Blue Ocean Marketing",
        email: "hello@blueocean.agency",
        services: "Digital Marketing, SEO, PPC",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Handled the successful launch campaign for KHIDMA.",
    },
    {
        id: "prov_8",
        name: "Fatima Al-Riyami",
        email: "fatima.r@hotmail.com",
        services: "Cybersecurity Auditing",
        status: "Pending Review",
        notes: "Certified ethical hacker. Application looks strong.",
    },
    {
        id: "prov_9",
        name: "Salim's Construction",
        email: "salim.con@gmail.com",
        services: "Subcontracting for physical installations",
        status: "On Hold",
        notes: "Unavailable for new contracts until October.",
    },
    {
        id: "prov_10",
        name: "The Content Crew",
        email: "editors@thecontentcrew.co",
        services: "Copywriting, Content Strategy",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Excellent for technical writing and blog posts.",
    },
    {
        id: "prov_11",
        name: "Innovate Labs",
        email: "rd@innovatelabs.dev",
        services: "R&D, Prototyping",
        status: "Pending Review",
        notes: "Potential partner for joint R&D projects.",
    },
    {
        id: "prov_12",
        name: "Oman Legal Consultants",
        email: "advice@omanlegal.co",
        services: "Legal Consultation (Corporate)",
        status: "Vetted",
        notes: "Our primary legal partner for contract reviews.",
    },
    {
        id: "prov_13",
        name: "Sultan Al-Maawali Photography",
        email: "sultan.photo@email.com",
        services: "Corporate Photography, Videography",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Did the headshots for the leadership team.",
    },
    {
        id: "prov_14",
        name: "Fast Track Couriers",
        email: "dispatch@fast-track.om",
        services: "Local Document & Package Delivery",
        status: "Vetted",
        notes: "Used for sealed document delivery.",
    },
    {
        id: "prov_15",
        name: "Amal Al-Zadjali",
        email: "amal.zadjali.translations@gmail.com",
        services: "Certified Legal Translation (Arabic/English)",
        status: "Pending Review",
        notes: "Applied to be a certified translation partner.",
    },
    {
        id: "prov_16",
        name: "Cloud Experts Inc.",
        email: "sales@cloudexperts.com",
        services: "Advanced Cloud Architecture (Azure/AWS)",
        status: "On Hold",
        notes: "High cost, but top-tier expertise. Holding for large projects.",
    },
    {
        id: "prov_17",
        name: "Digital Horizons",
        email: "team@digitalhorizons.co",
        services: "Social Media Management",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Manages social media for several key clients.",
    },
    {
        id: "prov_18",
        name: "Yousuf Al-Busaidi",
        email: "yousuf.busaidi@network.com",
        services: "Network & Systems Administration",
        status: "Vetted",
        notes: "Reliable for on-call IT support tasks.",
    },
    {
        id: "prov_19",
        name: "Salalah Animation Studios",
        email: "contact@salalah-animation.om",
        services: "2D/3D Animation, Motion Graphics",
        status: "Pending Review",
        portfolio: "https://example.com",
        notes: "Potential for creative projects and marketing videos.",
    },
    {
        id: "prov_20",
        name: "Strategic Insights Co.",
        email: "research@strategic-insights.co",
        services: "Market Research, Business Analysis",
        status: "On Hold",
        notes: "Specialized but expensive. Use for investor-facing reports.",
    },
    {
        id: "prov_21",
        name: "Hassan's IT Hardware",
        email: "sales@hassans-it.om",
        services: "Hardware Procurement",
        status: "Vetted",
        notes: "Good source for servers and networking equipment.",
    },
    {
        id: "prov_22",
        name: "Mariya Al-Hinai",
        email: "mariya.hinai.ux@gmail.com",
        services: "User Experience Research",
        status: "Pending Review",
        portfolio: "https://example.com",
        notes: "PhD in HCI. Could be valuable for product development.",
    },
    {
        id: "prov_23",
        name: "Sohar Web Security",
        email: "audits@sohar-sec.om",
        services: "Web Application Penetration Testing",
        status: "Vetted",
        notes: "Annual security audit partner.",
    },
    {
        id: "prov_24",
        name: "EventCrafters Oman",
        email: "planning@eventcrafters.om",
        services: "Corporate Event Management",
        status: "On Hold",
        notes: "Partner for physical events, currently no events planned.",
    },
    {
        id: "prov_25",
        name: "Digital Artistry Studios",
        email: "motion.graphics@studio.com",
        services: "Motion Graphics, 2D/3D Animation",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Created the animated logo for our PanoSpace product.",
    },
    {
        id: "prov_26",
        name: "Secure Code Audits",
        email: "audits@securecode.dev",
        services: "Smart Contract Auditing",
        status: "Pending Review",
        notes: "Specialized in blockchain security, relevant for 'ameen' project.",
    },
    {
        id: "prov_27",
        name: "Ahmed Al-Balushi",
        email: "ahmed.b.copy@email.com",
        services: "Arabic & English Copywriting",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Handles most of our marketing copy and press releases.",
    },
    {
        id: "prov_28",
        name: "Green Leaf Sustainability",
        email: "consult@greenleaf.om",
        services: "Sustainability & ESG Reporting",
        status: "On Hold",
        notes: "Potential partner for corporate social responsibility initiatives.",
    },
    {
        id: "prov_29",
        name: "Quantum Leap AI",
        email: "contact@quantumleapai.com",
        services: "Custom AI Model Development",
        status: "Pending Review",
        notes: "Expertise in custom model training, could assist Neo agent.",
    },
    {
        id: "prov_30",
        name: "Coastal Drone Services",
        email: "shots@coastaldrones.om",
        services: "Aerial Photography & Videography",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Provided aerial shots for our corporate video.",
    },
    {
        id: "prov_31",
        name: "Nizwa Data Solutions",
        email: "info@nizwadata.com",
        services: "Data Warehousing, ETL Pipelines",
        status: "Pending Review",
        notes: "Could help build out backend for Dana, the Data Analyst Agent.",
    },
    {
        id: "prov_32",
        name: "Layla Al-Harthi",
        email: "layla.harthi.pm@gmail.com",
        services: "Agile Project Management",
        status: "Vetted",
        notes: "Consults on large-scale projects to ensure agile methodologies are followed.",
    },
    {
        id: "prov_33",
        name: "The App Testers",
        email: "qa@theapptesters.com",
        services: "Quality Assurance & Manual Testing",
        status: "Vetted",
        notes: "Our go-to team for QA on all our product releases.",
    },
    {
        id: "prov_34",
        name: "Ibrahim Al-Said",
        email: "ibrahim.sa@gmail.com",
        services: "iOS & Android Development (Native)",
        status: "Pending Review",
        portfolio: "https://example.com",
        notes: "Strong native mobile development skills.",
    },
    {
        id: "prov_35",
        name: "Oman Datacenter Ops",
        email: "support@omandata.om",
        services: "On-premise Server Maintenance",
        status: "On Hold",
        notes: "For clients requiring physical server infrastructure.",
    },
    {
        id: "prov_36",
        name: "Sur Tech Writers",
        email: "docs@sur-tech.com",
        services: "Technical Documentation & API Guides",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Wrote the official documentation for our APPI product.",
    }
];

    
