
import type { z } from 'zod';
import type { ProviderSchema } from './providers.schema';

export type Provider = z.infer<typeof ProviderSchema>;

export const initialProviders: Provider[] = [
    {
        id: "prov_1",
        name: "Creative Solutions LLC",
        email: "contact@creativesolutions.io",
        services: "Web Development, UI/UX Design",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Reliable partner for several past projects. Excellent at React.",
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-06-15'),
    },
    {
        id: "prov_2",
        name: "Jane Doe Graphics",
        email: "jane.doe@gmail.com",
        services: "Branding, Logo Design, Illustration",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Winner of the last re-branding competition. Great creative eye.",
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-08-20'),
    },
    {
        id: "prov_3",
        name: "Muscat Tech Experts",
        email: "info@muscat-tech.om",
        services: "IT Support, Cloud Migration",
        status: "Pending Review",
        subscriptionTier: 'None',
        subscriptionExpiry: undefined,
    },
    {
        id: "prov_4",
        name: "Ali Al-Farsi",
        email: "ali.farsi.dev@proton.me",
        services: "Python, AI/ML, Data Scraping",
        status: "Pending Review",
        subscriptionTier: 'None',
        subscriptionExpiry: undefined,
    },
    {
        id: "prov_5",
        name: "Global Voiceovers",
        email: "talent@globalvoiceovers.com",
        services: "Voice Acting, Audio Production",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Provided voice work for the Voxi agent.",
        subscriptionTier: 'Lifetime',
        subscriptionExpiry: new Date('2099-12-31'),
    },
    {
        id: "prov_6",
        name: "Nasser Al-Habsi",
        email: "nasser.habsi@oman.net",
        services: "AR/VR Development (Unity)",
        status: "On Hold",
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2024-09-01'),
    },
    {
        id: "prov_7",
        name: "Blue Ocean Marketing",
        email: "hello@blueocean.agency",
        services: "Digital Marketing, SEO, PPC",
        status: "Vetted",
        portfolio: "https://example.com",
        notes: "Handled the successful launch campaign for KHIDMA.",
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-07-30'),
    },
    {
        id: "prov_8",
        name: "Fatima Al-Riyami",
        email: "fatima.r@hotmail.com",
        services: "Cybersecurity Auditing",
        status: "Pending Review",
        subscriptionTier: 'None',
        subscriptionExpiry: undefined,
    },
    {
        id: 'prov_9',
        name: 'Alpha Legal Translation',
        email: 'contact@alphalegal.om',
        services: 'Legal Document Translation, Attestation',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Specializes in court documents and contracts.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-05-20')
    },
    {
        id: 'prov_10',
        name: 'Sohar Web Works',
        email: 'dev@soharweb.co',
        services: 'PHP, WordPress, E-commerce',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Good for small to medium e-commerce projects.',
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-08-10')
    },
    {
        id: 'prov_11',
        name: 'Visionary VFX',
        email: 'contact@visionvfx.com',
        services: 'Video Editing, Motion Graphics, 3D Animation',
        status: 'Pending Review',
        portfolio: 'https://example.com',
        notes: 'New applicant with a strong portfolio in advertising.',
        subscriptionTier: 'None',
        subscriptionExpiry: undefined,
    },
    {
        id: 'prov_12',
        name: 'OmanCloud Host',
        email: 'support@omancloud.om',
        services: 'Cloud Hosting, Server Management, DevOps',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Provides reliable local hosting infrastructure.',
        subscriptionTier: 'Lifetime',
        subscriptionExpiry: new Date('2099-12-31')
    },
    {
        id: 'prov_13',
        name: 'Salalah Tech Solutions',
        email: 'info@salalahtech.om',
        services: 'IT Support, Network Installation',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Primary provider for the Dhofar region.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-04-01')
    },
    {
        id: 'prov_14',
        name: 'Ahmed Al-Lawati',
        email: 'ahmed.lawati@consultant.com',
        services: 'Financial Consulting, Business Planning',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Expert in SME financial health and fundraising.',
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-08-30')
    },
    {
        id: 'prov_15',
        name: 'The Copywriting Co-op',
        email: 'hello@copycoop.com',
        services: 'Copywriting, Content Strategy, Arabic Translation',
        status: 'Pending Review',
        portfolio: 'https://example.com',
        notes: 'A collective of freelance writers.',
        subscriptionTier: 'None',
        subscriptionExpiry: undefined,
    },
    {
        id: 'prov_16',
        name: 'Digital Falcons Agency',
        email: 'fly@digitalfalcons.net',
        services: 'Social Media Management, PPC, SEO',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Strong results in the B2C sector.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-07-01')
    },
    {
        id: 'prov_17',
        name: 'Mohammed Al-Ismaili',
        email: 'mo.ismaili@live.com',
        services: 'Mobile App Development (Flutter)',
        status: 'On Hold',
        portfolio: 'https://example.com',
        notes: 'Currently on a long-term project, unavailable for new work.',
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-08-05')
    },
    {
        id: 'prov_18',
        name: 'Sur Industrial Services',
        email: 'ops@surindustrial.om',
        services: 'HSE Consulting, Equipment Rental',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Key partner for projects in the Sharqiyah region.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-02-10')
    },
    {
        id: 'prov_19',
        name: 'Apex Accounting',
        email: 'audit@apexoman.com',
        services: 'Bookkeeping, Auditing, VAT Filing',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: '',
        subscriptionTier: 'Lifetime',
        subscriptionExpiry: new Date('2099-12-31')
    },
    {
        id: 'prov_20',
        name: 'Hassan Al-Ajmi Photography',
        email: 'hassan@ajmiphoto.com',
        services: 'Corporate Photography, Event Photography',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: '',
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-08-18')
    },
    {
        id: 'prov_21',
        name: 'Nizwa Software House',
        email: 'projects@nizwasoft.co',
        services: 'Custom Software Development, .NET, Java',
        status: 'Pending Review',
        portfolio: 'https://example.com',
        notes: '',
        subscriptionTier: 'None',
        subscriptionExpiry: undefined,
    },
    {
        id: 'prov_22',
        name: 'Samira Al-Zadjali',
        email: 'samira.zadjali@design.com',
        services: 'Interior Design, Architectural Visualization',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Helped design our new office space.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-01-15')
    },
    {
        id: 'prov_23',
        name: 'Musandam Logistics',
        email: 'shipping@musandamlogistics.om',
        services: 'Logistics, Customs Clearance, Freight Forwarding',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Our go-to partner for any logistics needs in Musandam.',
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-08-25')
    },
    {
        id: 'prov_24',
        name: 'Buraimi Digital Prints',
        email: 'print@buraimidigital.co',
        services: 'Large Format Printing, Signage, Vehicle Wraps',
        status: 'Pending Review',
        portfolio: 'https://example.com',
        notes: '',
        subscriptionTier: 'None',
        subscriptionExpiry: undefined,
    },
    {
        id: 'prov_25',
        name: 'LegalEase AI Solutions',
        email: 'info@legalease.ai',
        services: 'Legal Tech Consulting, AI Contract Analysis',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Consulted on the development of our Lexi Legal Agent.',
        subscriptionTier: 'Lifetime',
        subscriptionExpiry: new Date('2099-12-31')
    },
    {
        id: 'prov_26',
        name: 'Green Oasis Landscaping',
        email: 'garden@greenoasis.om',
        services: 'Landscaping, Garden Maintenance',
        status: 'On Hold',
        portfolio: 'https://example.com',
        notes: 'Seasonal business, mostly active in winter months.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-03-01')
    },
    {
        id: 'prov_27',
        name: 'The Research Hub',
        email: 'data@researchhub.co',
        services: 'Market Research, Surveys, Data Analysis',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Provide excellent data for our feasibility studies.',
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-08-28')
    },
    {
        id: 'prov_28',
        name: 'Khalfan Al-Harrasi',
        email: 'khalfan.h@gutech.edu.om',
        services: 'Academic Research, Technical Writing',
        status: 'Pending Review',
        portfolio: 'https://example.com',
        notes: '',
        subscriptionTier: 'None',
        subscriptionExpiry: undefined,
    },
    {
        id: 'prov_29',
        name: 'Cybernetic Systems',
        email: 'secure@cyberneticsys.com',
        services: 'Penetration Testing, Security Audits',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Certified ethical hackers.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-07-20')
    },
    {
        id: 'prov_30',
        name: 'Oman Event Planners',
        email: 'events@omanevents.co',
        services: 'Event Management, Conference Planning',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: '',
        subscriptionTier: 'Monthly',
        subscriptionExpiry: new Date('2024-08-12')
    },
    {
        id: 'prov_31',
        name: 'Innovate HR Consulting',
        email: 'hr@innovatehr.co',
        services: 'HR Policies, Recruitment, Performance Management',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Helped develop our internal HR framework.',
        subscriptionTier: 'Lifetime',
        subscriptionExpiry: new Date('2099-12-31')
    },
    {
        id: 'prov_32',
        name: 'The Brand Architects',
        email: 'studio@brandarchitects.design',
        services: 'Branding, UI/UX Design',
        status: 'On Hold',
        portfolio: 'https://example.com',
        notes: 'Fully booked for the next 3 months.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-01-01')
    },
    {
        id: 'prov_33',
        name: 'Fast Track PRO Services',
        email: 'pro@fasttrack.om',
        services: 'Government Liaison, Visa Processing, Document Clearance',
        status: 'Vetted',
        portfolio: 'https://example.com',
        notes: 'Highly efficient and knowledgeable about government processes.',
        subscriptionTier: 'Yearly',
        subscriptionExpiry: new Date('2025-06-30')
    }
];
    
