
export interface Worker {
    id: string;
    name: string;
    nationality: string;
    age: number;
    skills: string[];
    experience: string;
    availability: 'Available' | 'Not Available';
    rating: number;
    photo: string;
    agencyId: 'Happy Homes Agency' | 'Premier Maids';
}

export const initialRaahaWorkers: Worker[] = [
    {
        id: 'worker_001',
        name: 'Maria Dela Cruz',
        nationality: 'Filipino',
        age: 32,
        skills: ['Childcare', 'Cooking (Asian)', 'General Cleaning', 'English Speaking'],
        experience: 'Over 8 years of experience working as a housemaid and nanny for families in the UAE and Oman. Excellent with young children and infants.',
        availability: 'Available',
        rating: 4.8,
        photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=600&auto=format&fit=crop',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_002',
        name: 'Siti Nurhaliza',
        nationality: 'Indonesian',
        age: 28,
        skills: ['Elderly Care', 'Cooking (Arabic)', 'Laundry & Ironing', 'Basic Arabic'],
        experience: '5 years of experience as a caregiver for an elderly couple in Muscat. Patient and compassionate.',
        availability: 'Available',
        rating: 4.6,
        photo: 'https://images.unsplash.com/photo-1610216705422-caa3fcb6d158?q=80&w=600&auto=format&fit=crop',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_003',
        name: 'Anjali Sharma',
        nationality: 'Indian',
        age: 35,
        skills: ['Deep Cleaning', 'Cooking (Indian)', 'Organizing', 'Pet Care'],
        experience: '10 years of experience managing large households in India and Bahrain. Expert in deep cleaning and home organization.',
        availability: 'Not Available',
        rating: 4.9,
        photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_004',
        name: 'Fatuma Mohammed',
        nationality: 'Ethiopian',
        age: 25,
        skills: ['General Cleaning', 'Cooking (Basic)', 'Washing', 'Hardworking'],
        experience: '3 years of experience in Oman as a general housemaid. Learns quickly and is very diligent.',
        availability: 'Available',
        rating: 4.4,
        photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
        agencyId: 'Premier Maids',
    },
     {
        id: 'worker_005',
        name: 'Amina Begum',
        nationality: 'Bangladeshi',
        age: 30,
        skills: ['General Cleaning', 'Cooking (Bangladeshi)', 'Laundry', 'Follows Instructions Well'],
        experience: '4 years of experience with a family in Sohar. Known for being reliable and efficient.',
        availability: 'Available',
        rating: 4.5,
        photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600&auto=format&fit=crop',
        agencyId: 'Happy Homes Agency',
    },
     {
        id: 'worker_006',
        name: 'Kumari Perera',
        nationality: 'Sri Lankan',
        age: 40,
        skills: ['Childcare (All Ages)', 'Cooking (International)', 'First Aid Certified', 'Excellent English'],
        experience: '15 years of experience as a nanny and house manager for expatriate families in Dubai. Highly recommended.',
        availability: 'Available',
        rating: 5.0,
        photo: 'https://images.unsplash.com/photo-1554151228-14d9def656e4?q=80&w=600&auto=format&fit=crop',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_007',
        name: 'Mercy Wanjiru',
        nationality: 'Kenyan',
        age: 29,
        skills: ['Elderly Care', 'General Cleaning', 'English Speaking'],
        experience: '6 years of experience in Qatar, specializing in providing compassionate care for elderly clients.',
        availability: 'Available',
        rating: 4.7,
        photo: 'https://picsum.photos/seed/worker7/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_008',
        name: 'Rose Nakato',
        nationality: 'Ugandan',
        age: 26,
        skills: ['Childcare', 'Cooking (African)', 'General Cleaning'],
        experience: 'New to the Gulf region, 2 years of experience in a large family household in Kampala. Energetic and eager to learn.',
        availability: 'Available',
        rating: 4.2,
        photo: 'https://picsum.photos/seed/worker8/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_009',
        name: 'Priya Patel',
        nationality: 'Indian',
        age: 38,
        skills: ['Cooking (Vegetarian)', 'Cooking (Indian)', 'Deep Cleaning', 'Organizing'],
        experience: 'Over 12 years of experience as a cook and housekeeper. Specializes in vegetarian and South Indian cuisines.',
        availability: 'Not Available',
        rating: 4.8,
        photo: 'https://picsum.photos/seed/worker9/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_010',
        name: 'Lia Lestari',
        nationality: 'Indonesian',
        age: 31,
        skills: ['Childcare (Toddlers)', 'General Cleaning', 'Laundry & Ironing'],
        experience: '4 years with an expatriate family in Muscat. Very patient and good with toddlers and young children.',
        availability: 'Available',
        rating: 4.6,
        photo: 'https://picsum.photos/seed/worker10/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_011',
        name: 'Jasmin Reyes',
        nationality: 'Filipino',
        age: 34,
        skills: ['House Management', 'Cooking (International)', 'Driving License (Oman)', 'English Speaking'],
        experience: 'Experienced House Manager with an Omani driving license. Can run errands, manage household budgets, and supervise other staff.',
        availability: 'Available',
        rating: 4.9,
        photo: 'https://picsum.photos/seed/worker11/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_012',
        name: 'Bimala Thapa',
        nationality: 'Nepalese',
        age: 27,
        skills: ['General Cleaning', 'Hardworking', 'Mountain endurance'],
        experience: '2 years of experience in a hotel housekeeping department in Dubai. Very high standards of cleanliness.',
        availability: 'Available',
        rating: 4.5,
        photo: 'https://picsum.photos/seed/worker12/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_013',
        name: 'Zahara Ali',
        nationality: 'Tanzanian',
        age: 30,
        skills: ['Cooking (Arabic)', 'Childcare', 'Basic Arabic', 'General Cleaning'],
        experience: '5 years of experience in Saudi Arabia and Oman. Fluent in Swahili and Arabic.',
        availability: 'Not Available',
        rating: 4.7,
        photo: 'https://picsum.photos/seed/worker13/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_014',
        name: 'Gladys Owuor',
        nationality: 'Kenyan',
        age: 33,
        skills: ['Elderly Care', 'First Aid Certified', 'English Speaking', 'General Cleaning'],
        experience: 'Certified nursing assistant with 7 years of experience in a care home in Kenya. Seeking a position as a private caregiver.',
        availability: 'Available',
        rating: 4.9,
        photo: 'https://picsum.photos/seed/worker14/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_015',
        name: 'Rina Wulandari',
        nationality: 'Indonesian',
        age: 29,
        skills: ['General Cleaning', 'Cooking (Indonesian)', 'Laundry & Ironing'],
        experience: '3 years with a family in Al Khuwair. Works well independently.',
        availability: 'Available',
        rating: 4.5,
        photo: 'https://picsum.photos/seed/worker15/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_016',
        name: 'Lakshmi Devi',
        nationality: 'Indian',
        age: 42,
        skills: ['Cooking (South Indian)', 'Cooking (Vegetarian)', 'Childcare'],
        experience: 'Over 20 years of experience as a family cook. Can manage a kitchen for a large family and events.',
        availability: 'Available',
        rating: 4.8,
        photo: 'https://picsum.photos/seed/worker16/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_017',
        name: 'Mary Ann Flores',
        nationality: 'Filipino',
        age: 28,
        skills: ['Childcare (Newborn)', 'General Cleaning', 'English Speaking', 'Organizing'],
        experience: '4 years of experience, including 2 years as a maternity nanny. Excellent references.',
        availability: 'Not Available',
        rating: 4.9,
        photo: 'https://picsum.photos/seed/worker17/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_018',
        name: 'Sonia Akter',
        nationality: 'Bangladeshi',
        age: 24,
        skills: ['General Cleaning', 'Washing', 'Hardworking'],
        experience: '2 years of experience in a small apartment setting. Very neat and tidy.',
        availability: 'Available',
        rating: 4.3,
        photo: 'https://picsum.photos/seed/worker18/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_019',
        name: 'Brenda Auma',
        nationality: 'Ugandan',
        age: 31,
        skills: ['General Cleaning', 'Cooking (Basic)', 'English Speaking'],
        experience: '5 years working in hotels in Dubai. Now looking for a position in a private home.',
        availability: 'Available',
        rating: 4.5,
        photo: 'https://picsum.photos/seed/worker19/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_020',
        name: 'Sunita Rai',
        nationality: 'Nepalese',
        age: 29,
        skills: ['Childcare', 'General Cleaning', 'Cooking (Nepalese)'],
        experience: '3 years of experience as a nanny for a family with school-aged children.',
        availability: 'Available',
        rating: 4.6,
        photo: 'https://picsum.photos/seed/worker20/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_021',
        name: 'Elia Putri',
        nationality: 'Indonesian',
        age: 35,
        skills: ['Elderly Care', 'Patience', 'Cooking (Indonesian)', 'General Cleaning'],
        experience: '10 years experience specializing in care for elderly clients with mobility issues.',
        availability: 'Available',
        rating: 4.9,
        photo: 'https://picsum.photos/seed/worker21/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_022',
        name: 'Cristina Mercado',
        nationality: 'Filipino',
        age: 45,
        skills: ['House Management', 'Supervising Staff', 'Cooking (International)', 'Driving License (Oman)'],
        experience: 'Former hotel head housekeeper with 20+ years experience. Ideal for managing a large villa or estate.',
        availability: 'Not Available',
        rating: 5.0,
        photo: 'https://picsum.photos/seed/worker22/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_023',
        name: 'Hanna Abebe',
        nationality: 'Ethiopian',
        age: 28,
        skills: ['General Cleaning', 'Basic Arabic', 'Cooking (Ethiopian)'],
        experience: '4 years experience with a family in Muscat. Good understanding of local culture.',
        availability: 'Available',
        rating: 4.5,
        photo: 'https://picsum.photos/seed/worker23/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_024',
        name: 'Geeta Singh',
        nationality: 'Indian',
        age: 33,
        skills: ['Childcare (School-age)', 'Tutoring', 'Cooking (North Indian)'],
        experience: 'Former teacher with 5 years experience as a nanny/tutor for children aged 6-12.',
        availability: 'Available',
        rating: 4.8,
        photo: 'https://picsum.photos/seed/worker24/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_025',
        name: 'Rahma Yusuf',
        nationality: 'Tanzanian',
        age: 29,
        skills: ['General Cleaning', 'Laundry & Ironing', 'Cooking (Swahili)'],
        experience: '3 years of experience working in a large family home in Dar es Salaam. First time in the Gulf.',
        availability: 'Available',
        rating: 4.3,
        photo: 'https://picsum.photos/seed/worker25/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_026',
        name: 'Angelica Bautista',
        nationality: 'Filipino',
        age: 30,
        skills: ['Pet Care', 'General Cleaning', 'English Speaking'],
        experience: '5 years of experience, including 3 years in a household with multiple pets (dogs & cats).',
        availability: 'Available',
        rating: 4.7,
        photo: 'https://picsum.photos/seed/worker26/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_027',
        name: 'Dewi Anggraini',
        nationality: 'Indonesian',
        age: 36,
        skills: ['Cooking (Pastries & Baking)', 'Cooking (International)', 'General Cleaning'],
        experience: 'Trained as a pastry cook. 8 years experience as a house cook for various families.',
        availability: 'Not Available',
        rating: 4.9,
        photo: 'https://picsum.photos/seed/worker27/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_028',
        name: 'Faith Mwangi',
        nationality: 'Kenyan',
        age: 24,
        skills: ['General Cleaning', 'Hardworking', 'Follows Instructions Well'],
        experience: '1 year of experience in a commercial cleaning company. Eager to work in a domestic setting.',
        availability: 'Available',
        rating: 4.2,
        photo: 'https://picsum.photos/seed/worker28/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_029',
        name: 'Lalita Devi',
        nationality: 'Indian',
        age: 39,
        skills: ['Elderly Care', 'Cooking (Indian)', 'Hindi Speaking'],
        experience: '10 years experience providing live-in care for elderly individuals in India. Very patient and caring.',
        availability: 'Available',
        rating: 4.7,
        photo: 'https://picsum.photos/seed/worker29/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_030',
        name: 'Irene Ocampo',
        nationality: 'Filipino',
        age: 37,
        skills: ['General Cleaning', 'Organizing', 'English Speaking', 'Childcare'],
        experience: '12 years of experience with expatriate families in Singapore and Hong Kong. Highly organized and professional.',
        availability: 'Available',
        rating: 5.0,
        photo: 'https://picsum.photos/seed/worker30/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_031',
        name: 'Chaltu Girma',
        nationality: 'Ethiopian',
        age: 28,
        skills: ['General Cleaning', 'Cooking (Basic)', 'Laundry & Ironing'],
        experience: '3 years of dedicated service with one family in Bahrain. Good with children.',
        availability: 'Available',
        rating: 4.5,
        photo: 'https://picsum.photos/seed/worker31/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_032',
        name: 'Nisha Rana',
        nationality: 'Nepalese',
        age: 30,
        skills: ['Childcare', 'General Cleaning', 'Cooking (Nepalese)'],
        experience: '5 years of experience as a nanny and housekeeper in Qatar. Loves children.',
        availability: 'Not Available',
        rating: 4.6,
        photo: 'https://picsum.photos/seed/worker32/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_033',
        name: 'Yuni Lestari',
        nationality: 'Indonesian',
        age: 29,
        skills: ['General Cleaning', 'Cooking (Indonesian)', 'Hardworking'],
        experience: '4 years with a family in Kuwait. Very efficient and detail-oriented cleaner.',
        availability: 'Available',
        rating: 4.7,
        photo: 'https://picsum.photos/seed/worker33/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_034',
        name: 'Joyce Achieng',
        nationality: 'Kenyan',
        age: 34,
        skills: ['Elderly Care', 'Cooking (African)', 'English Speaking'],
        experience: '8 years of experience as a professional caregiver for seniors. Certified in first aid and CPR.',
        availability: 'Available',
        rating: 4.9,
        photo: 'https://picsum.photos/seed/worker34/600/600',
        agencyId: 'Premier Maids',
    },
    {
        id: 'worker_035',
        name: 'Sarita Khanal',
        nationality: 'Nepalese',
        age: 26,
        skills: ['General Cleaning', 'Laundry & Ironing', 'Cooking (Basic)'],
        experience: '2 years working in Malaysia in a private residence. Strong and hardworking.',
        availability: 'Available',
        rating: 4.4,
        photo: 'https://picsum.photos/seed/worker35/600/600',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'worker_036',
        name: 'Precy Reyes',
        nationality: 'Filipino',
        age: 41,
        skills: ['House Management', 'Cooking (Asian)', 'Childcare', 'English Speaking'],
        experience: '18 years of experience in high-end households in Hong Kong. Excellent organizational skills.',
        availability: 'Available',
        rating: 5.0,
        photo: 'https://picsum.photos/seed/worker36/600/600',
        agencyId: 'Premier Maids',
    }
];
