
import type { HireRequest } from './raaha-requests.schema';

export const initialRequests: HireRequest[] = [
    {
        id: 'req_01',
        workerId: 'worker_001',
        workerName: 'Maria Dela Cruz',
        clientName: 'Ahmed Al-Farsi',
        clientContact: '+968 99123456',
        requestDate: '2024-07-28T10:00:00Z',
        status: 'Pending',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'req_02',
        workerId: 'worker_002',
        workerName: 'Siti Nurhaliza',
        clientName: 'Fatima Al-Balushi',
        clientContact: 'fatima.b@example.com',
        requestDate: '2024-07-27T15:30:00Z',
        status: 'Contacted',
        agencyId: 'Premier Maids',
    },
    {
        id: 'req_03',
        workerId: 'worker_006',
        workerName: 'Kumari Perera',
        clientName: 'Expat Family Residences',
        clientContact: 'manager@expatres.com',
        requestDate: '2024-07-26T11:00:00Z',
        status: 'Interviewing',
        agencyId: 'Happy Homes Agency',
        interviewDate: '2024-08-05T14:00:00Z',
        interviewNotes: 'Zoom call scheduled. Link sent to client.',
    },
    {
        id: 'req_04',
        workerId: 'worker_007',
        workerName: 'Mercy Wanjiru',
        clientName: 'David Smith',
        clientContact: '+971 50 123 4567',
        requestDate: '2024-07-29T09:00:00Z',
        status: 'Pending',
        agencyId: 'Premier Maids',
    },
    {
        id: 'req_05',
        workerId: 'worker_011',
        workerName: 'Jasmin Reyes',
        clientName: 'Al Bustan Palace Hotel',
        clientContact: 'hr@bustanpalace.com',
        requestDate: '2024-07-29T12:00:00Z',
        status: 'Interviewing',
        agencyId: 'Happy Homes Agency',
        interviewDate: '2024-08-02T10:30:00Z',
        interviewNotes: 'In-person interview at the hotel lobby.',
    },
    {
        id: 'req_06',
        workerId: 'worker_014',
        workerName: 'Gladys Owuor',
        clientName: 'Nasser Al-Khalili',
        clientContact: 'nasser.k@gmail.com',
        requestDate: '2024-07-28T18:00:00Z',
        status: 'Contacted',
        agencyId: 'Premier Maids',
    },
    {
        id: 'req_07',
        workerId: 'worker_021',
        workerName: 'Elia Putri',
        clientName: 'Aisha Al-Harthy',
        clientContact: '+968 98765432',
        requestDate: '2024-07-25T14:00:00Z',
        status: 'Hired',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'req_08',
        workerId: 'worker_026',
        workerName: 'Angelica Bautista',
        clientName: 'The Pet Care Center',
        clientContact: 'info@petcareoman.com',
        requestDate: '2024-07-24T10:30:00Z',
        status: 'Closed',
        agencyId: 'Premier Maids',
    },
    {
        id: 'req_09',
        workerId: 'worker_004',
        workerName: 'Fatuma Mohammed',
        clientName: 'Salim Al-Rahbi',
        clientContact: 'salim.rahbi@yahoo.com',
        requestDate: '2024-07-30T11:00:00Z',
        status: 'Pending',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'req_10',
        workerId: 'worker_010',
        workerName: 'Lia Lestari',
        clientName: 'The Johnson Family',
        clientContact: '+1 202 555 0192',
        requestDate: '2024-07-29T16:20:00Z',
        status: 'Pending',
        agencyId: 'Premier Maids',
    },
    {
        id: 'req_11',
        workerId: 'worker_016',
        workerName: 'Lakshmi Devi',
        clientName: 'Indian School Muscat',
        clientContact: 'principal@ismoman.com',
        requestDate: '2024-07-22T09:00:00Z',
        status: 'Hired',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'req_12',
        workerId: 'worker_015',
        workerName: 'Rina Wulandari',
        clientName: 'Abdullah Al-Hinai',
        clientContact: '+968 91112222',
        requestDate: '2024-07-28T13:45:00Z',
        status: 'Contacted',
        agencyId: 'Premier Maids',
    },
    {
        id: 'req_13',
        workerId: 'worker_030',
        workerName: 'Irene Ocampo',
        clientName: 'The British Embassy',
        clientContact: 'facilities@britishembassy.om',
        requestDate: '2024-07-27T10:00:00Z',
        status: 'Interviewing',
        agencyId: 'Happy Homes Agency',
        interviewDate: '2024-08-01T09:00:00Z',
        interviewNotes: 'First round interview via Teams.',
    },
    {
        id: 'req_14',
        workerId: 'worker_034',
        workerName: 'Joyce Achieng',
        clientName: 'Senior Care Homes LLC',
        clientContact: 'careers@seniorcare.om',
        requestDate: '2024-07-26T17:00:00Z',
        status: 'Interviewing',
        agencyId: 'Premier Maids',
        interviewDate: '2024-08-04T11:00:00Z',
        interviewNotes: 'Group interview session.',
    },
    {
        id: 'req_15',
        workerId: 'worker_001',
        workerName: 'Maria Dela Cruz',
        clientName: 'Maryam Al-Zadjali',
        clientContact: 'maryam.z@gmail.com',
        requestDate: '2024-07-25T19:00:00Z',
        status: 'Closed',
        agencyId: 'Happy Homes Agency',
    },
    {
        id: 'req_16',
        workerId: 'worker_005',
        workerName: 'Amina Begum',
        clientName: 'Al Qurum Resort',
        clientContact: 'housekeeping@qurumresort.com',
        requestDate: '2024-07-30T08:30:00Z',
        status: 'Pending',
        agencyId: 'Premier Maids',
    },
    {
        id: 'req_17',
        workerId: 'worker_024',
        workerName: 'Geeta Singh',
        clientName: 'The International School',
        clientContact: 'hr@tis.edu.om',
        requestDate: '2024-07-29T14:00:00Z',
        status: 'Contacted',
        agencyId: 'Happy Homes Agency',
    },
     {
        id: 'req_18',
        workerId: 'worker_036',
        workerName: 'Precy Reyes',
        clientName: 'Royal Opera House Muscat',
        clientContact: 'vip-services@rohmuscat.org.om',
        requestDate: '2024-07-23T12:00:00Z',
        status: 'Hired',
        agencyId: 'Premier Maids',
    }
];
