
'use client';

import { useGlobalStore, useSetStore } from '@/lib/global-store.tsx';

export const useProductsData = () => useGlobalStore(state => ({ data: state.products, setData: state.set, isClient: state.isClient }));
export const useStoreProductsData = () => useGlobalStore(state => ({ data: state.storeProducts, isClient: state.isClient }));
export const useProvidersData = () => useGlobalStore(state => ({ data: state.providers, setData: state.set, isClient: state.isClient }));
export const useOpportunitiesData = () => useGlobalStore(state => ({ data: state.opportunities, setData: state.set, isClient: state.isClient }));
export const useServicesData = () => useGlobalStore(state => ({ data: state.services, setData: state.set, isClient: state.isClient }));
export const useStaffData = () => useGlobalStore(state => ({ leadership: state.leadership, staff: state.staff, agentCategories: state.agentCategories, set: state.set, isClient: state.isClient }));
export const useCfoData = () => useGlobalStore(state => ({ data: state.cfoData, setData: state.set, isClient: state.isClient }));
export const useAssetsData = () => useGlobalStore(state => ({ data: state.assets, setData: state.set, isClient: state.isClient }));
export const usePropertiesData = () => useGlobalStore(state => ({ data: state.properties, setData: state.set, isClient: state.isClient }));
export const useStairspaceListingsData = () => useGlobalStore(state => ({ data: state.stairspaceListings, setData: state.set, isClient: state.isClient }));
export const useStairspaceRequestsData = () => useGlobalStore(state => ({ data: state.stairspaceRequests, setData: state.set, isClient: state.isClient }));
export const useLeasesData = () => useGlobalStore(state => ({ data: state.signedLeases, setData: state.set, isClient: state.isClient }));
export const useStockItemsData = () => useGlobalStore(state => ({ data: state.stockItems, setData: state.set, isClient: state.isClient }));
export const useGiftCardsData = () => useGlobalStore(state => ({ data: state.giftCards, setData: state.set, isClient: state.isClient }));
export const useStudentsData = () => useGlobalStore(state => ({ data: state.students, setData: state.set, isClient: state.isClient }));
export const useCommunitiesData = () => useGlobalStore(state => ({ data: state.communities, setData: state.set, isClient: state.isClient }));
export const useCommunityEventsData = () => useGlobalStore(state => ({ data: state.communityEvents, setData: state.set, isClient: state.isClient }));
export const useMembersData = () => useGlobalStore(state => ({ data: state.communityMembers, setData: state.set, isClient: state.isClient }));
export const useAlumniJobsData = () => useGlobalStore(state => ({ data: state.alumniJobs, setData: state.set, isClient: state.isClient }));
export const useCarsData = () => useGlobalStore(state => ({ data: state.cars, setData: state.set, isClient: state.isClient }));
export const usePosProductsData = () => useGlobalStore(state => ({ data: state.posProducts, setData: state.set, isClient: state.isClient }));
export const useBriefcaseData = () => useGlobalStore(state => ({ briefcase: state.briefcase, setBriefcaseData: state.set, isClient: state.isClient }));
export const useKnowledgeBaseData = () => useGlobalStore(state => ({ data: state.knowledgeBase, setData: state.set, isClient: state.isClient }));
export const useClientsData = () => useGlobalStore(state => ({ data: state.clients, setData: state.set, isClient: state.isClient }));
export const useTestimonialsData = () => useGlobalStore(state => ({ data: state.testimonials, setData: state.set, isClient: state.isClient }));
export const useStagesData = () => useGlobalStore(state => ({ data: state.stages, setData: state.set, isClient: state.isClient }));
export const useRequestsData = () => useGlobalStore(state => ({ data: state.raahaRequests, setRequests: state.set, isClient: state.isClient }));
export const useAgenciesData = () => useGlobalStore(state => ({ data: state.raahaAgencies, setData: state.set, isClient: state.isClient }));
export const useWorkersData = () => useGlobalStore(state => ({ data: state.raahaWorkers, setData: state.set, isClient: state.isClient }));
export const useBeautyCentersData = () => useGlobalStore(state => ({ data: state.beautyCenters, setData: state.set, isClient: state.isClient }));
export const useBeautySpecialistsData = () => useGlobalStore(state => ({ data: state.beautySpecialists, setData: state.set, isClient: state.isClient }));
export const useBeautyServicesData = () => useGlobalStore(state => ({ data: state.beautyServices, setData: state.set, isClient: state.isClient }));
export const useBeautyAppointmentsData = () => useGlobalStore(state => ({ data: state.beautyAppointments, setData: state.set, isClient: state.isClient }));
export const useUsedItemsData = () => useGlobalStore(state => ({ data: state.usedItems, setData: state.set, isClient: state.isClient }));
export const useCartData = () => useGlobalStore(state => ({ cart: state.cart, setCart: state.set, isClient: state.isClient }));
export const useSettingsData = () => useGlobalStore(state => ({ settings: state.settings, setSettings: state.set, isClient: state.isClient }));
export const useCostSettingsData = () => useGlobalStore(state => ({ data: state.costSettings, setData: state.set, isClient: state.isClient }));
export const usePricingData = () => useGlobalStore(state => ({ data: state.pricing, setData: state.set, isClient: state.isClient }));
