query ListProjects {
  projects {
    id
    name
    description
  }
}

query ListUsersByOrganization($organizationId: UUID!) {
  users(where: {organizationId: {eq: $organizationId}}) {
    id
    displayName
    email
  }
}

mutation UpdateTask($id: UUID!, $status: String!) {
  task_update(
    id: $id
    data: {status: $status}
  )
}
