mutation InsertOrganization {
  organization_insert(
    data: { name: "Firebase", createdAt: "now()" }
  ) {
    id
  }
}
query ListUsersByOrganization($organizationId: UUID!) {
  users(
    where: { organization_id: { eq: $organizationId } }
    orderBy: { id: ASC }
  ) {
    id
    displayName
    email
  }
}
query ListProjects {
  projects {
    id
    name
    description
  }
}
mutation UpdateTask($id: UUID!, $status: String!) {
  task_update(
    where: { id: { eq: $id } }
    data: { status: $status }
  ) {
    id
  }
}
