
'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/tender-response-assistant';
import '@/ai/flows/ai-powered-faq.ts';
import '@/ai/flows/social-media-post-generator.ts';
import '@/ai/flows/legal-agent';
import '@/ai/flows/cv-enhancement.ts';
import '@/ai/flows/letter-of-interest';
import '@/ai/flows/work-order-analysis.ts';
import '@/ai/flows/train-agent.ts';
import '@/ai/flows/image-generator.ts';
import '@/ai/flows/partnership-inquiry';
import '@/ai/flows/document-translation.ts';
import '@/ai/flows/cr-analysis.ts';
import '@/ai/flows/identity-analysis.ts';
import '@/ai/flows/meeting-analysis';
import '@/ai/flows/generate-agreement.ts';
import '@/ai/flows/interview-coach.ts';
import '@/ai/flows/whatsapp-agent.ts';
import '@/ai/flows/project-inception';
import '@/ai/flows/financial-document-analysis.ts';
import '@/ai/flows/cctv-quotation.ts';
import '@/ai/flows/floor-plan-analysis.ts';
import '@/ai/flows/it-rental-agent.ts';
import '@/ai/flows/sanad-task-analysis.ts';
import '@/ai/flows/sanad-office-registration';
import '@/ai/flows/business-hub-agent';
import '@/ai/flows/text-to-speech.ts';
import '@/ai/flows/ecommerce-agent.ts';
import '@/ai/flows/pro-task-analysis.ts';
import '@/ai/flows/subscription-reminders.ts';
import '@/ai/flows/web-scraper-agent.ts';
import '@/ai/flows/feasibility-study.ts';
import '@/ai/flows/ameen-smart-lock.ts';
import '@/ai/flows/video-generator.ts';
import '@/ai/flows/coupon-generator.ts';
import '@/ai/flows/knowledge-document-analysis.ts';
import '@/ai/flows/image-annotation';
import '@/ai/flows/boq-generator.ts';
    
