
'use server';
import { config } from 'dotenv';
config();

import '@/ai/flows/tender-response-assistant.ts';
import '@/ai/flows/ai-powered-faq.ts';
import '@/ai/flows/social-media-post-generator.ts';
import '@/ai/flows/legal-agent.ts';
import '@/ai/flows/cv-enhancement.ts';
import '@/ai/flows/letter-of-interest.ts';
import '@/ai/flows/work-order-analysis.ts';
import '@/ai/flows/train-agent.ts';
import '@/ai/flows/image-generator.ts';
import '@/ai/flows/partnership-inquiry.ts';
import '@/ai/flows/document-translation.ts';
import '@/ai/flows/cr-analysis.ts';
import '@/ai/flows/identity-analysis.ts';
import '@/ai/flows/meeting-analysis.ts';
import '@/ai/flows/generate-agreement.ts';
import '@/ai/flows/interview-coach.ts';
import '@/ai/flows/whatsapp-agent.ts';
import '@/ai/flows/project-inception.ts';
import '@/ai/flows/financial-document-analysis.ts';
import '@/ai/flows/cctv-quotation.ts';
import '@/ai/flows/floor-plan-analysis.ts';
import '@/ai/flows/it-rental-agent.ts';
import '@/ai/flows/sanad-task-analysis.ts';
import '@/ai/flows/sanad-office-registration.ts';
import '@/ai/flows/sanad-office-registration.schema.ts';
import '@/ai/flows/business-hub-agent.ts';
import '@/ai/flows/text-to-speech.ts';
import '@/ai/flows/text-to-speech.schema.ts';
import '@/ai/flows/ecommerce-agent.ts';
import '@/ai/flows/ecommerce-agent.schema.ts';
import '@/ai/flows/pro-task-analysis.ts';
import '@/ai/flows/pro-task-analysis.schema.ts';
import '@/ai/flows/subscription-reminders.ts';
import '@/ai/flows/web-scraper-agent.ts';
import '@/ai/flows/feasibility-study.ts';
import '@/ai/flows/ameen-smart-lock.ts';
import '@/ai/flows/video-generator.ts';
    